### ISSUE TITLE
Request for Provenance Hash 

### ISSUE THREAD

**Issue by johnswifttt** [hashlips-lab/nft-erc721-collection#1]
First, just want to say thank you for providing this amazing library!

My question is in regards to Provenance Hash. There are many projects that implement this such as Bored Ape Yacht Club. I really like this [article](https://medium.com/coinmonks/the-elegance-of-the-nft-provenance-hash-solution-823b39f99473) that goes over the high-level concept.

Will you be adding support for a provenance hash to this library? I guess it's not much, maybe just this:

```solidity 
string public PROVENANCE_HASH = "";

function setProvenanceHash(string memory provenanceHash) public onlyOwner {
    PROVENANCE_HASH = provenanceHash;
}
```

If you do add support for this, would creating the provenance hash be a part of this repo or instead the HashLips Art Engine repo? From what I see, it seems HashLips Art Engine does not support it yet.

**Comment by AlfieDarko** [comment]
I second this as it provides NFT minters wit abit more reassurance that they are not getting hustled.

**Comment by laygir** [comment]
Indeed would be nice to have it.. 
I've something working locally but It should be part of Hashlips Art Engine for sure.

if you like to give it a try take a look at these commits

https://github.com/nftchef/art-engine/commits/nested-folder-structure/utils/provenance.js

**Comment by liarco** [comment]
Hi everyone, thank you for your feedback. 😃 We really care about this topic a lot and I must say it's already in our plans for future stuff, but as @laygir already pointed out: most of the work for it has to be done in the art-engine which is what we are gonna focus our efforts in the next weeks and months.

We absolutely have to take care of how to generate the proper metadata, before adding functions to this contract. The solidity file in this project is completely customizable so anyone can add the `setProvenanceHash(...)` function and its contract field if needed, but we will introduce that by default only when we can provide a solid solution to generate the hash.

I'm gonna close this issue in order to keep the repository clean, but we will use this as a reference for any update about this topic.

Thank you for your understanding.

**Comment by johnswifttt** [comment]
@liarco thank you! Looking forward to updates!

**Comment by johnswifttt** [comment]
> Indeed would be nice to have it.. I've something working locally but It should be part of Hashlips Art Engine for sure.
> 
> if you like to give it a try take a look at these commits
> 
> https://github.com/nftchef/art-engine/commits/nested-folder-structure/utils/provenance.js

@laygir Thank you for reference NFTChef library. Quick question, how could one verify that this library creates the provenance hash correctly? For example, once we create the provenance hash, is there a website, terminal command, or something to verify it's correct?

**Comment by laygir** [comment]
hey @johnswifttt 

The hash is created based on the image itself and it's a one way hash. We don't want to reverse verify the hash, so there is no incorrectness.

Notice the line written in the article you shared on the original post

> So what is a hash? A hash is simply a one-way conversion of data to a string


Getting the hash of the image is like the snapshot of the image but from byte/data perspective so to say.  Imagine, if we were to modify 1 pixel of the image and hash it again, the result would be totally different but as a viewer we may not notice the difference. Since a modification was made, those two hashes do not match any more which suggests the second image in our example was indeed modified and not the original.

But don't forget, there are 2 steps. First we hash each image in the collection. If our collection was to have a 500 piece, we would end up with 500 individual hashes.

The provenance hash is the hash of hashes. Meaning we concatenate all 500 hashes we gathered in above sentence one after other, then we end up with one very long string, then we hash this long string to reach to our provenance hash.

Then we, as the contract/collection owner have the responsibility to publish these 500 hashes + 1 provenance hash on a public page before we deploy or minting start date. (This is the promise and accountability we provide to the public and a way of giving them the fingerprint of the image without giving them the actual image before minting) 

Idea is to prove our audience that we are not going to temper with the images we have published/teased to gain their trust and attention.

**Now come to the verification part:**
Once the collection is revealed, token owners can use the same algorithm (sha-256 usually) to hash the image at their hand. Now the expected result is the hash we have published on our public page for that specific token id matches the hash we generated with same token id as the owner..

This doesn't have to be done by owners of course, since images are revealed, anybody who is suspecious or concerned of authenticity may perform this operation.

Bored Ape's website is doing a very good job on this https://boredapeyachtclub.com/#/provenance

I hope I didn't confuse you further, but I think the article you shared originally is doing a very good job on explaining the concept and flow. Hope this helps ✌️

**Comment by johnswifttt** [comment]
@laygir Great explanation! I ran through an example based on what you said using BAYC and really interesting!

## Test verifying hash of a single image

1. I went to Bored Ape's website for provenance hash: https://boredapeyachtclub.com/#/provenance
2. Downloaded the imaged linked to token `0` here: <img width="1010" alt="Screen Shot 2022-02-19 at 5 35 17 PM" src="https://user-images.githubusercontent.com/10701375/154821309-339a801c-2f85-42c0-b6ea-850e035dc7b1.png">
3. Uploaded the image to this website using SHA256 hash: https://emn178.github.io/online-tools/sha256_checksum.html
4. I got the same hash! The hash is `c92b0386542d8beb8fb167aed611e73c5f30250a083f54edf78653946a8a6913` and this matches what is on Bored Ape's website. 
<img width="300" alt="Screen Shot 2022-02-19 at 5 36 58 PM" src="https://user-images.githubusercontent.com/10701375/154821349-76e373af-eb25-4ea0-9d31-326773e73ec2.png">

 ## Test verifying Provenance Hash

1. I went to Bored Ape's website for provenance hash: https://boredapeyachtclub.com/#/provenance
2. Copied the concatenated hash string here: <img width="1139" alt="Screen Shot 2022-02-19 at 5 42 50 PM" src="https://user-images.githubusercontent.com/10701375/154821511-86e24555-a160-471a-8661-d337441592a5.png">
3. Pasted the concatenated hash string here: https://emn178.github.io/online-tools/sha256.html
4. Perfect! The provenance hash matches what's on the website here:`cc354b3fcacee8844dcc9861004da081f71df9567775b3f3a43412752752c0bf`:
<img width="1383" alt="Screen Shot 2022-02-19 at 5 45 41 PM" src="https://user-images.githubusercontent.com/10701375/154821607-178a56f5-03de-499a-84a8-87b61c40cc65.png">

## Summary

Learned a lot thanks to you explanation!!

There are still some things I need to learn from BAYC provenance webpage such as:
- Not sure why this formula is important: `(tokenId + startingIndex) % 10000 → Initial Sequence Index`
- Not sure how/why `FINALIZED STARTING INDEX` is determined 
- Not sure purpose of `ARWEAVE PERMAWEB URIS`

<img width="1125" alt="Screen Shot 2022-02-19 at 5 48 25 PM" src="https://user-images.githubusercontent.com/10701375/154821685-f279004f-7715-493f-8962-c54fffecd05e.png">
