### ISSUE TITLE
How to use contract , if don't have hidden meta and we want to put base uri of our own json file ?

### ISSUE THREAD

**Issue by Wajid4040** [hashlips-lab/nft-erc721-collection#101]
Hi thanks a lot for smart contract , I have a question if I don't have hidden metadata and directly want to use my base URI in at the time of deployment then how I can do this ? thanks a lot

**Comment by liarco** [comment]
Hi @Wajid4040 a proper and clean way to do this would involve changes in many parts of the code and I can't support you with this here. You should ask this type of question on the Discord server or hire a developer for that.

I'm gonna leave you a quick proof of concept so you might be able to test it at least, but as I said: despite this might work, I would not recommend using it for production.

Replace the following line:
https://github.com/hashlips-lab/nft-erc721-collection/blob/0c723c1c6eb90eb6281c66c9e83bb090f525c2a5/smart-contract/contracts/YourNftToken.sol#L17

With this:
```solidity
    string public uriPrefix = 'ipfs://__REVEALED_METADATA_CID__/';
```

And also replace this line:
https://github.com/hashlips-lab/nft-erc721-collection/blob/0c723c1c6eb90eb6281c66c9e83bb090f525c2a5/smart-contract/contracts/YourNftToken.sol#L27

With this:
```solidity
    bool public revealed = true;
```

I hope this helps.

**Comment by Wajid4040** [comment]
thanks a lot for your help this worked Sir , actually I put this question on discord first but no one replies

**Comment by liarco** [comment]
It's not easy to get help for free, so you have to try many times until someone has some free time and decides to help you out. Otherwise you can always hire a dev from the dedicated channels (even for a small paid advice).

I don't want to push you into spending money, but I must point out that if you don't have the knowledge to make this change on your own, then you won't be able to know if there are side-effects that may ruin your project. 😉

**Comment by Wajid4040** [comment]
Thanks Sir , I cannot hire developer yet cause it's my age of learning and I am just 12

**Comment by liarco** [comment]
Oh, ok, if you are just learning that's absolutely fine. You can test everything with no pressure, my previous statements were for people creating actual projects, because you should never run a real collection project if you don't know how things work! 😉

Anyway, keep learning, it's awesome to start at that age! 😃

**Comment by Wajid4040** [comment]
I tried above suggestion  you know before deploy the contract we have to copy some input data as hiddenmetauri was not filled it was not going to let me copy , what I did it I removed as they were in public as well from contractor and also from function now it's fine

**Comment by liarco** [comment]
I'm sorry but I don't understand what you did exactly... everything should work fine even if you leave it as is... simply leave the placeholder for the "hiddenMetadataUri" and it's gonna ignore it since your collection will start as revealed directly.

**Comment by Wajid4040** [comment]
> I'm sorry but I don't understand what you did exactly... everything should work fine even if you leave it as is... simply leave the placeholder for the "hiddenMetadataUri" and it's gonna ignore it since your collection will start as revealed directly.

Yup but I am until I will not initialize the contractor elements it will not allow me to copy the input elements ABI, which I need to verify the contract, One more question I applied it to polygon mainnet but suppose I mint 50 then it shows only five on the open sea, does it support only eth

Request :
               I wanted to be a Good dev like you , do you have any youtube channel or anything other source where I can learn from you ! or keep me assistant of yours (just kidding ) sir

**Comment by liarco** [comment]
@Wajid4040 deployment on Polygon is not supported yet so there might be issues (it should come with the next version), but in this case I think that the problem should be with OpenSea (if you're using the testnets version it can take very long sometimes). Also, this project gives you all the tools you need in order to verify your contract by running a very simple command, so you should need to use the ABI manually.

> Request :
> I wanted to be a Good dev like you , do you have any youtube channel or anything other source where I can learn from you ! or keep me assistant of yours (just kidding ) sir

Thank you, I really appreciate it. My YouTube channel is pretty new, but I plan to keep adding content as much as possible, here is the link: http://www.youtube.com/channel/UCsNUSP49XDIhxaZoZlLwnyw

**Comment by Wajid4040** [comment]
Thanks a lot, sir for replying I have checked your youtube channel You are too Young, Oh  I see therefore I was having issues with matic network.
I really want to test gas estimation on this contract on eth mainnet , I have tried to check on rinkenby but it shows the same gas units on every transaction 

I have read everything in erc721A Pr , on this repository but I have also done as much research I can ! but Have some question in mind 

1) does  to deploy our collection will cost us only ( deploy + 1 nft minting price ) 
2) Can I mint my 10000 collection  under 1000 USD, with 25 gwei average gas price on etherscan , 

I am really sorry if I am talking lot but this is all my saving therefore I was curious that I can deploy my collection real eth mainnet cause I have seen on polygon there is no importance much for nfts
