### ISSUE TITLE
Minting DAPP works perfect on my local server but not when I build and upload the files to cpanel I get a blank page?

### ISSUE THREAD

**Issue by JSwizzleCrypto** [hashlips-lab/nft-erc721-collection#102]
The entire process has worked perfectly for me! I successfully ran the DAPP on my local dev server and it works like a charm! But when I build it and go to upload it to my cpanel subdomain (mint.”my url”) I just get a blank white page? I have been trying to solve this issue for days and can’t seem to find the solution, really hope I can get some help!

**Comment by liarco** [comment]
Hi @JSwizzleCrypto,
please answer some questions:
1. did you upload to the root path?
2. which files did you upload?

**Comment by JSwizzleCrypto** [comment]
Yes my subdomain is inside the root path!

I uploaded the build folder / index.html, which is what I was told to upload by Hashlips! 

Not sure what I am doing incorrectly? Do I need to direct the files to the subdomain folder?

**Comment by liarco** [comment]
@JSwizzleCrypto it should say to upload everything from the `/minting-dapp/public` folder, so you also have to upload the `build` folder too.

**Comment by JSwizzleCrypto** [comment]
Now I’m confused? 

What files am I suppose to upload? I uploaded the build folder as well as the index.html file is that not what I’m suppose to upload?

**Comment by JSwizzleCrypto** [comment]
Also thank you for responding so quickly, I have been trying to figure this out forever!

**Comment by JSwizzleCrypto** [comment]
I just doubled checked the only things in the public folder are the build folder and index.html which is what I uploaded. So what is the issue?

**Comment by liarco** [comment]
No problem, can you please upload here a screenshot showing the files inside the `build` folder? (GitHub supports drag&drop) for images.

Thank you

**Comment by JSwizzleCrypto** [comment]
![dapp_troubleshooting](https://user-images.githubusercontent.com/98909849/157460638-a7a9551f-fead-4773-8975-2bd15ae633e9.png)

**Comment by JSwizzleCrypto** [comment]
![dapp_build](https://user-images.githubusercontent.com/98909849/157460663-afcceaa8-292e-4501-81c1-e20a896884dd.png)

**Comment by JSwizzleCrypto** [comment]
Here you go! Thanks for the help again, this has been frustrating me for a couple days now.

**Comment by JSwizzleCrypto** [comment]
This is it looks like?

**Comment by liarco** [comment]
I'm sorry @JSwizzleCrypto , everything looks fine... a part from the last screenshot. I'm trying to access that URL in order to understand whats happening there, but it's says it's forbidden. Anyway, from the screenshot, it seems like it's failing loading the content of the `build` folder, but that must be a deployment error in my opinion.

Unfortunately I cant give you support for this specific case, since the DAPP is building fine (no errors) and the files in the first two screenshots look exactly how they should (you would miss something for it to fail so badly).
It seems like there is some error in the way you are deploying the files to your hosting provider. Maybe you can ask for help on HashLips' Discord server.

**Comment by JSwizzleCrypto** [comment]
What did you close the case? Literally nothing was resolved wtf?

**Comment by JSwizzleCrypto** [comment]
Hello?

**Comment by JSwizzleCrypto** [comment]
Other people in the discord are getting the exact same issue, so how could that make sense? Only thing we all have in common in the dApp?

**Comment by liarco** [comment]
@JSwizzleCrypto , there are really a lot of people using this project at the moment, this would be the first time ever that I see that blank page and that it's not the dev's fault...

But never say never... please make so that I can access the DAPP from my browser and give me the link here. I'm gonna try do understand what's going on as soon as I have some free time.

**Comment by JSwizzleCrypto** [comment]
I emailed you but Im not sure if you it went through? I emailed a link to you! Let me know if you received it/ need anymore links or resources! Thanks again!

**Comment by liarco** [comment]
@JSwizzleCrypto  I'm sorry but I didn't receive any e-mail from you, anyway I used the link in the screenshot above and it seems like you did it wrong.

As you can see from the Chrome inspector all of your assets files return a 404 error:
<img width="645" alt="Screen Shot 2022-03-10 at 13 47 12" src="https://user-images.githubusercontent.com/1532277/157664745-fdb6f677-7a0d-41a8-b564-686efe9850e5.png">

Opening one of them shows that the requested path is `/build/main.css` which is totally correct:
<img width="645" alt="Screen Shot 2022-03-10 at 13 48 03" src="https://user-images.githubusercontent.com/1532277/157664880-309be1d0-193b-4969-9e0a-26eb3494a799.png">

But you didn't upload the `build` folder as is (as we instructed you to do), you placed all the files together in the root path:
<img width="665" alt="Screen Shot 2022-03-10 at 13 52 14" src="https://user-images.githubusercontent.com/1532277/157665602-9e4a80fd-eae7-4491-bb12-76ebbd7115ca.png">

So, I'm sorry to reiterate this, but as I stated from the beginning: this was not our fault, so please avoid writing messages like the previous ones because it's disrespectful. It's totally fine not to be an expert, but you should take your time to learn how the basics work before telling people that they have to fix your own mistakes.

**Comment by JSwizzleCrypto** [comment]
@liarco Hey, 

That was only because I w a messing around last night and trying everything! 

When I upload the files exactly like you said they still do not work! 

I can show you, it just be something in my code, I just don’t know what?

I called my hosting service yesterday and they said the issue was with the information contained within the index.html file

**Comment by JSwizzleCrypto** [comment]
I have tried to fix the problem for over 24 hours now, I have tried every single thing I can think of and that I find on the internet! I really hope you can find a solution!

**Comment by JSwizzleCrypto** [comment]
Also I have learned the basics, numerous people on the discord are running into this same issue, and no one has yet to find a solution! Called my hosting service and there is 100% no issue with them, they tested it and it’s an issue with the code! I am just trying to find out what that issue is so I can fix it! And although I know the basics sifting through the code to find a small error in code that works is very hard to do! And that is where I’m really asking you for help as an expert on this code specifically! 

Thanks again for everything and I really hope you get back to me with a solution @liarco

**Comment by JSwizzleCrypto** [comment]
@liarco just put the files back to the way I had them (how you guys say in the video) and I am getting the exact same error. 

http://mint.babyslothclub.com/

Here is the link if you could like to check it out for yourself!

**Comment by JSwizzleCrypto** [comment]
I can also send screenshots of the code, I just don't know what else to try at this point.

**Comment by liarco** [comment]
Please clear your cache...

<img width="722" alt="Screen Shot 2022-03-10 at 15 42 17" src="https://user-images.githubusercontent.com/1532277/157685414-9ec87660-3c25-454d-a33c-90bf93cba269.png">

**Comment by JSwizzleCrypto** [comment]
I will gladly send you anything else you need, screenshot of code or
anything!

I have tried every solution I can find and nothing has helped, so I really
hope you can help me!

Thanks again, you are a lifesaver!

James

**Comment by JSwizzleCrypto** [comment]
Hey,

That was only because I w a messing around last night and trying
everything!

When I upload the files exactly like you said they still do not work!

I can show you, it just be something in my code, I just don’t know what?

I called my hosting service yesterday and they said the issue was with the
information contained within the index.html file

**Comment by liarco** [comment]
Hi @JSwizzleCrypto, I'm sorry but I'm not sure I understand what you need.
We already released many [video tutorials](https://github.com/hashlips-lab/nft-erc721-collection#youtube-tutorials) about how to use this tool, including one about [deploying the Dapp](https://youtu.be/uUrbIXUgVz4) specifically.
A lot of people are using this tool with no issues and more experienced devs have also been able to deploy to different hosting solutions.
Unfortunately, we cannot support every hosting provider available out there, it's up to the devs to know how to make the Dapp work with a custom hosting platform if they decide not to use the suggested one.
