### ISSUE TITLE
truffle not working after installing

### ISSUE THREAD

**Issue by Lypheal** [hashlips-lab/nft-erc721-collection#108]
After I've installed truffle using _npm i -g truffle_, I am getting this error when I run _truffle dashboard_:

node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'C:\Users\Lypheal\AppData\Roaming\npm\node_modules\truffle\build\cli.bundled.js'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) 
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

**Comment by liarco** [comment]
Hi @Lypheal,
unfortunately this issue is not related to our specific project so I can't help with it. I also have no experience on Windows machines so I'm not even able to try replicating the issue.

You might try to ask on [Truffle's GitHub repo](https://github.com/trufflesuite/truffle/issues), StackOverflow or even the HashLips' Discord.

**Comment by burningrex** [comment]
i am getting problem after truffle dashboard : 
truffle : File C:\Users\rplam\AppData\Roaming\npm\truffle.ps1 cannot be loaded because running scripts is disabled on this system. For more information, see about_Execution_Policies at 
https:/go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:1
+ truffle dashboard
+ ~~~~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess

fml.. i've gotten so far and yet so far away
