### ISSUE TITLE
My ticket was closed before I could respond...

### ISSUE THREAD

**Issue by JSwizzleCrypto** [hashlips-lab/nft-erc721-collection#109]
I couldn't say this in the other Thread because its closed but ...

@liarco This may be a stupid question but do you mean my browser cache? Or some other cache?

Because I cleared my browser cache but that didn't do anything?

**Comment by JSwizzleCrypto** [comment]
Can you please just help with this one last thing, I still can't get it to show up but somehow you can?

**Comment by liarco** [comment]
@JSwizzleCrypto this is my last warning: stop spamming on issues.

> I couldn't say this in the other Thread because its closed but ...

First of all, you can reply to closed issues (anyone can do it and you already did it so many times, so I don't understand your statement). If you continue opening new useless issues I will be forced to report your account.

> @liarco This may be a stupid question but do you mean my browser cache? Or some other cache?

This is not a stupid question, it's simply that you lack the basic knowledge in order to do what you are trying to do and I cannot teach you about that. You should take your time to learn with proper courses/platforms or you should hire a developer.

> Because I cleared my browser cache but that didn't do anything?

Same as above.

> Can you please just help with this one last thing, I still can't get it to show up but somehow you can?

I'm sorry, I can't. Please respect my time. You should hire a developer that knows how to deal with web applications.

**Comment by liarco** [comment]
> Wow that was extremely rude. At no point was I ever rude, just asking for help.

I'm sorry to hear this, I respect your opinion, but I personally do not agree. #102 and #103 should be self-explanatory.
