### ISSUE TITLE
Thank You page for Minting-Dapp site

### ISSUE THREAD

**Issue by gitrevo** [hashlips-lab/nft-erc721-collection#11]
Hi team,

It would be cool to have a redirection to a thank you (success) page after user successfully minted (whitelist/presale/public). Right now, it will remain or stucked in the minting page even user had successfully minted and confirmed the transaction via MetaMask. There is no indication the minting of token was successful except by visiting Etherscan or check wallet activity.

Appreciate it with thanks Daniel and Marko.

**Comment by liarco** [comment]
Hi @gitrevo,
thank you for your feedback, this sounds interesting and it is already planned for the future. We just need to find some time to work on it (or maybe we can review some proposals from the community).

My main requirements for this feature are the following:
1. I would show an in-page "thank you" message rather than redirecting outside the DAPP
2. we should start with a minimal implementation, so a basic message (maybe customized based on the sale step) and we may show a link to OpenSea/Etherscan to view the confirmed operation
3. to explain point (2) a bit further: I received requests for stuff like "token preview on successful mint", etc... I see these as overkill since most of the time tokens would not even be revealed. As always: K.I.S.S.

I hope this will come soon. 😃

**Comment by gitrevo** [comment]
Hi @liarco,

Agreed, K.I.S.S. is the way to go.

Same like you did with “Contract pause”, we could just change the texts to:

——
“1 Token(s) minted successfully”.
View on Etherscan: https://etherscan.io/tx/hash
Button: Back to Main Page
——
P/s: Or can change “1” to tokenID(s)

Minimalism is recommended on the minting-dapp :) Looking forward to implement this on our project.

Thanks Marco.

**Comment by erick3166** [comment]
I might be wrong but it sounds like the op goal is to track conversions from a sales funnel. This could be accomplished with analytics and creating a defined action to count towards a conversion. You can even set dollar amounts and it's used widely to track one page sites. goodluck! An easy tool is tag manager.

**Comment by gitrevo** [comment]
> I might be wrong but it sounds like the op goal is to track conversions from a sales funnel. This could be accomplished with analytics and creating a defined action to count towards a conversion. You can even set dollar amounts and it's used widely to track one page sites. goodluck! An easy tool is tag manager.

Hi, thanks for your suggestion. Now that you had mentioned it; it might be useful to track conversion as well. But my main objective was to set a clear indication what happened after user successfully minted, for some they may thought that the minting process hasn’t completed which may lead them to redo the minting again.

**Comment by liarco** [comment]
I think we might fire some events and let people attach listeners to them in order to support any tracking platform.

Anyway we won't introduce any direct support for analytics platforms since then we would have to manage cookies and preferences through a built-I'm solution and it's way beyond the scope of this project.
I see many DAPPs using analytics scripts without users' permission and that behavior should not be encouraged.😉

**Comment by erick3166** [comment]
Marco is right about the cookies, it's encouraged to add this to your website and dependent on how you would want to track conversions or where. Google offers implementation of the script and it's managed through them. That's a whole new discussion, there's many ways to implement analytics, what's in compliance, why it should be used, how long, etc..... Overall tracking conversions through a funnel allows you to to benefit from being able to see what works for your concept or not and prevent exhausting your resources on something that may not be effective towards your goals. Your goal could be to sell a million NFTS or it could be to build a community with no existing monetization (for now). The power of analytics is to provide you with a clearer path on how you can accomplish your goals and there are so many ways on doing that. Well this would be a different topic lol...

**Comment by VeriumNFT** [comment]
I would also like to say thank you before this issue is closed. This project is incredible and I look forward to viewing your walk-through and support videos. 🙌

**Comment by dhararughani** [comment]
hey Liarco , can you please tell me where do i find the mint button function inside the code. I want to redesign the minting dapp. But I need to know where is the main the minting function is written.

**Comment by liarco** [comment]
@dhararughani if you plan doing this type of customization I would highly suggest studying the whole codebase (it's not much). Also, this question is off-topic...

Anyway: https://github.com/hashlips-lab/nft-erc721-collection/blob/dd21ef539cfdc02052f0bd7e6544020969adf2db/minting-dapp/src/scripts/react/Dapp.tsx#L84-L100

**Comment by basememara** [comment]
I created PR #178 that disables action buttons and renders a success message with details on how to track and view the NFT. I attached a video to take a look. Feedback and testing welcome. Thank you @liarco for the foundation!

**Comment by slavakurilyak** [comment]
+1 for post-mint status message or modal

**Comment by Ali-JNM** [comment]
Thank you All hashlips-labs organization ,you really did the awsome job
