### ISSUE TITLE
Re-Opening public-sale after reveal

### ISSUE THREAD

**Issue by granthughes1999** [hashlips-lab/nft-erc721-collection#110]
After you run Yarn Reveal, the collection will be successfully revealed on opensea with metadata. 

However, if you go back to the smart-contract terminal and run  yarn public-sale-open --network truffle and process the request on the truffle dashboard. The minting-dapp published on a static host sever will in fact reopen the public sale. This is not the issue.

 The issue is while people are able to mint and the money will be moved into the contract and transactions will be successful. The NFTs do NOT appear in that person's wallet or in the collection on Opensea. I waited 12 hours to make sure, and they never appeared on Opensea, or the minter's wallet!

This will most likely be an issue for those who do not sell out and still want to reveal their collection. As they might go back and try to re-open their minting. I will test leaving the public-sale-open and running yarn reveal. I believe this will work, but I have not verified. 

Just a piece of caution, and a possible thing to look into.  

Thanks,

**Comment by liarco** [comment]
Hi @granthughes1999,
thank you for your feedback, I think we have to go a bit deeper in this because it should not be possible. Revealing the collection doesn't affect the sale stages in any way (at least not that I'm aware of).

Would you please share the testing contract where this is happening? Having some example transaction hashes would also be useful.

Thank you very much!

**Comment by granthughes1999** [comment]
Of course @liarco,

Contract Address Polyscan 
[0x8CCCF5Fd8b204e26c2EA75D53965437e7CF01014 
](https://polygonscan.com/address/0x8CCCF5Fd8b204e26c2EA75D53965437e7CF01014)

Transaction Hash of 10 Successful Mints.
[0x3975218055646d06fcd416036e01c414720320c58a9306d1e5dccc0701b999aa](https://polygonscan.com/tx/0x3975218055646d06fcd416036e01c414720320c58a9306d1e5dccc0701b999aa)
These 10 Mints took place after I had run yarn reveal, and then re-run yarn public-sale-open --network truffle.

As you can see on the main polyscan page for this contract, the contract was revealed shown by this tx hash
[0xab009a461955aab6c0a9773c1de99add43336626712510d0a5e27b7c4bad1002](https://polygonscan.com/tx/0xab009a461955aab6c0a9773c1de99add43336626712510d0a5e27b7c4bad1002)
But the 10 Mints do not show up here. Now that I'm looking the tx hash for running yarn public-sale-open is not shown in the contracts transaction history either..?

Thanks,

**Comment by liarco** [comment]
Thank you @granthughes1999 the information is great.

⚠️ First of all, even if I don't think this has anything to do with this, I must say that you are using this app on Polygon and this is not supported yet. ⚠️

I took a look at all the data you provided and I must say that I don't see anything strange (on the blockchain side).

> What's also odd, is that I do not see the history for the yarn public-sale-open in my metmask account that I deployed the contract from. I also do not see the the transaction in my metamask for the 10 mints.

Some transactions might be missing on MetaMask (you can also reset your transaction history in MM settings). But all the transactions are visible on Polygonscan and that's what matters.

> i was testing this feature specifically. also, the money was removed from my metamask account and was moved into the contract because I withdrew it directly after. the minting-dapp also updated to have +10 in the supply section.

This is also what the blockchain tells me, because I can see all of your transactions, including the call to the `mint()` function for your 10 tokens.
Here is the transaction: https://polygonscan.com/tx/0x3975218055646d06fcd416036e01c414720320c58a9306d1e5dccc0701b999aa
And here are your tokens: https://polygonscan.com/address/0x4fd899ba1384274817ab84417293dd4d569fc71a#tokentxnsErc721

They are there on the blockchain so everything seems to be working fine.

> The minting-dapp shows 10 extra in the supply than is shown on the opensea collection.

But the minting DAPP is correct here, you can tell even from the "Contract" tab on Polygonscan where the numbers match with the DAPP. So it seems like OpenSea is not updating the supply for some reason.

> There is no tx history in the contract for the yarn public-sale-open, yet I am still able to mint from the minting-dapp.. even though the last recorded tx on the contract was ["set Paused"](https://polygonscan.com/tx/0x6e73debbba1f6fa952d13e9c46a643cc891be8e063395b890a152011660df238)

This is also fine, because that TX is calling the `setPaused()` function, but it's passing `false` as argument (`setPause(false)`) so the contract is unpaused and the sale should be open.

> [Here](https://goofy-benz-e8790c.netlify.app/) is the minting-dapp if you want to take a look at it

To me the DAPP is working perfectly fine, all the data there matches Polygonscan. OpenSea, on the other hand, is not showing the correct data and I have no idea why to be honest...

> For some extra info. Those 10 mints that are no where to be found, took place directly after I re-opened the public-sale after the reveal was done.

To my knowledge there shouldn't be any correlation between these two things.

------

### Another strange thing that might be related to your issue:
You told me that the contract address is [`0x8CCCF5Fd8b204e26c2EA75D53965437e7CF01014`](https://polygonscan.com/address/0x8CCCF5Fd8b204e26c2EA75D53965437e7CF01014) and that the failing transaction is [`0x3975218055646d06fcd416036e01c414720320c58a9306d1e5dccc0701b999aa`](https://polygonscan.com/tx/0x3975218055646d06fcd416036e01c414720320c58a9306d1e5dccc0701b999aa), but the address that run this transaction is `0x4fd899ba1384274817ab84417293dd4d569fc71a` and if I go to that [profile on OpenSea](https://opensea.io/0x4fd899BA1384274817AB84417293Dd4d569fC71A) I see that there is no token from that contract. Not even one...
All the tokens you see there are from other contract addresses, you can see it here:
<img width="724" alt="Screen Shot 2022-03-10 at 17 52 44" src="https://user-images.githubusercontent.com/1532277/157714041-83cd4a38-fa80-4d65-a2ab-f86bc6ca0185.png">

Are you sure you added the collection properly on OpenSea? Because I suspect you forgot to do that for this specific contract and maybe you are jus confused because you see some tokens from previous tests...

**Comment by granthughes1999** [comment]
@liarco,

well, I do apologize, I was apparently testing this too late at night. After re-checking my notes, this transaction is on the blockchain, I had the order of events wrong in my head. everything on the blockchain does add up perfectly to my notes. the issue is certainly on Openseas side, for not revealing the correct images. because there are 10 NFTs still missing on the collection. 

To be clear there are Mints from this address 0x4fd899ba1384274817ab84417293dd4d569fc71a to this contract on Opensea, as can be seen [here](https://opensea.io/assets/matic/0x8cccf5fd8b204e26c2ea75d53965437e7cf01014/22).

once again you solved my issues. karma for you will be large in life my good sir. 

Thank you,

**Comment by liarco** [comment]
@granthughes1999 don't worry, that happens! I'm happy to hear everything seems to be working fine, now let's hope OpenSea will refresh the data about that collection... 😉
