### ISSUE TITLE
Replacing Images in SRC/images folder

### ISSUE THREAD

**Issue by ArabianAce** [hashlips-lab/nft-erc721-collection#111]
@liarco Replacing images in SRC/images folder under minting dapp did not automatically update the images under Build/images
or Should i need to replace images in both destinations or should I need to build minting-dapp once again for it to automatically replace everywhere?

**Comment by liarco** [comment]
Oh sorry, I'm so used to this kind of stuff that I didn't mention it: you always have to rebuild the app every time you make a change to the source. The only exception is when using `yarn dev-server` because in that case almost any change would trigger an automated rebuild and refresh on your browser.

Let me know if this helps.

**Comment by ArabianAce** [comment]
i rebuilt it yes. Worked out. Now should i pick a whole "Public folder" to go on to my server root directory or just the sub folders "Index.html" and "Build"?

**Comment by ArabianAce** [comment]
No error came. We are live on server. Feeling very good

**Comment by ArabianAce** [comment]
Thank you so so so much 
Love you for everything.
