### ISSUE TITLE
Adding royalties walk through  

### ISSUE THREAD

**Issue by granthughes1999** [hashlips-lab/nft-erc721-collection#112]
@liarco 

Could you Verify that this is where you would add [Openseas](https://docs.opensea.io/docs/contract-level-metadata) code for adding royalties?

1. You add the line below to smart-contracts/contracts/yourNFTproject.sol file
and you would add it inside the contract like this 

contract TestWolvesPolygon3 is ERC721A, Ownable, ReentrancyGuard {
    using Strings for uint256;

  function contractURI() public view returns (string memory) {
        return "https://metadata-url.com/my-metadata";
    }
}

2. on [Openseas](https://docs.opensea.io/docs/contract-level-metadata) guide it provides this .json file example.

{
  "name": "OpenSea Creatures",
  "description": "OpenSea Creatures are adorable aquatic beings primarily for demonstrating what can be done using the OpenSea platform. Adopt one today to try out all the OpenSea buying, selling, and bidding feature set.",
  "image": "https://openseacreatures.io/image.png",
  "external_link": "https://openseacreatures.io",
  "seller_fee_basis_points": 100, # Indicates a 1% seller fee.
  "fee_recipient": "0xA97F337c39cccE66adfeCB2BF99C1DdC54C2D721" # Where seller fees will be paid to.
}

Should this now be the layout of the hidden.json file you use in your contract. so you would create this .json, upload it and use the associated CID# in the CollectionConfifg.ts for the hiddenMetadataUri: 'ipfs://CID#/hidden.json',.

Is this everything?

Thanks you!!

**Comment by liarco** [comment]
Hi @granthughes1999,
I hope in your understanding when I say that I can't provide you with suggestions about some code that I never tried (and that I don't have time to try on your behalf). This is something that is out of the scope of this repo (and by the way I already told in other issues that I don't agree with this solution from OpenSea).

My suggestion might be:
1. follow the guide step by step
2. test it very well before using it
3. remember that that URI is hard-coded there, so if it goes away I don't know how OpenSea might react and if they would allow you to change something from their website (I think the should disable the settings page if your contract contains that function)

> Should this now be the layout of the hidden.json file you use in your contract. so you would create this .json, upload it and use the associated CID# in the CollectionConfifg.ts for the hiddenMetadataUri: 'ipfs://CID#/hidden.json',.

No, that JSON data is something else, specific to OpenSea and has nothing to do with other metadata for your collection. OpenSea is gonna call that function in order to grab that metadata from your server, then it's gonna use it as settings for your collection.
