### ISSUE TITLE
Minting Dapp Background

### ISSUE THREAD

**Issue by meltapollo** [hashlips-lab/nft-erc721-collection#115]
Hello Hashlips and Liarco, First off want to say thank you for all your hard work! Second i want to go over a problem ive been having with the new minting dapp! So i want to add a custom background onto the dapp instead of the stock blank white image. I dont see any folders / files with a background file to change like the older dapp had in the "images" folder. How would i go about to change the background to my preference? Thank you for reading / responding!! <3

**Comment by liarco** [comment]
Hi @meltapollo,
thank you for your feedback! Please take a look at this: https://github.com/hashlips-lab/nft-erc721-collection/issues/46#issuecomment-1054274405

I suggest using search before opening issues because you might already find the answer to your question and this avoids having a lot of duplicates around. 😉
