### ISSUE TITLE
Smart-Contract

### ISSUE THREAD

**Issue by Patrizi5** [hashlips-lab/nft-erc721-collection#117]
![Screenshot (5)](https://user-images.githubusercontent.com/97971328/157984006-77994d5d-2a56-4e85-bb41-bf5221596e6f.png)

**Comment by liarco** [comment]
@Patrizi5, please read this carefully, because this is really important: I had to delete several duplicate messages in many issues where you posted this exact same picture asking for help. It took me time to clean up the issues and this shouldn't happen anymore.

The screen you attached shows a clear error message: `Cannot fine path '...' because it doesn't exist`. In order to use this tool you should have at least a basic knowledge about out to use a terminal (e.g. moving between folders and running commands). If you are a beginner and you don't know how to use the tools required in order to run our project, then you should learn from [my YouTube channel](http://www.youtube.com/channel/UCsNUSP49XDIhxaZoZlLwnyw), [HashLips' YouTube channel](https://www.youtube.com/channel/UC1LV4_VQGBJHTJjEWUmy8nA) or the [Discord server](https://discord.gg/qh6MWhMJDN).

I'm sorry but I can't help you explaining this kind of things because this is not the right place. Here you should report bugs in our software, this is not a bug.
