### ISSUE TITLE
Created new Deploy, How to interact with old contract ?

### ISSUE THREAD

**Issue by granthughes1999** [hashlips-lab/nft-erc721-collection#118]
I created a new deployed contract and now I'm not sure how to interact with the old deployed contract? Is there a way to switch between deployed contracts?

**Comment by liarco** [comment]
Hi @granthughes1999, if you made changes to the code this might be impossible (it depends on the changes you made). If you didn't change the code between your deployments then setting the contract address should be enough to switch back to the old one.

Anyway I highly suggest using a different project for each collection in order to avoid this kind of issues.

I'm gonna close this issue since it's not strictly related to this project (it's more about the Hardhat framework), but feel free to reply below if you need further information.
