### ISSUE TITLE
Installing tailwind 

### ISSUE THREAD

**Issue by monsterhive123** [hashlips-lab/nft-erc721-collection#126]
@liarco Hi Liarco could you please help me with tailwind I've tried installing tailwind on the dapp multiple times but it doesn't work.  Also, could you please expand on this please "possibility to start designing from scratch in no-time (simply deleting the SCSS code)" do u replace scss with CSS? I've been trying to edit the HTML with tailwind but it doesn't work it only works when I use this script <script src="https://cdn.tailwindcss.com"></script> but adding this messes up the mint button? How do I fix this thanks?
![156398971-f06b9303-b8fc-493c-b204-d713d0f3bcf6](https://user-images.githubusercontent.com/96693503/158096763-09b6ca57-5bd7-4070-9d4c-b85d8947d1c4.png)
![image](https://user-images.githubusercontent.com/96693503/158096812-b210c88e-8f02-4e24-acdb-3310de724faa.png)

**Comment by CaptainJoyboy** [comment]
Im no tailwind expert, but I think we are loading tailwind in the context of the React app, not at the HTML level. Having said this, I would recommend adding the `<div class="footer ...` element as part of the HTML being returned in the render function of the Dapp.tsx file 
```
render() {
    return (
      <div className="outer">
         ...
         <div classname="footer__legal....>...</div>
      </div>
```

PS: wasn't there already a footer in the example HTML returned by the render function?

**Comment by liarco** [comment]
Hi @monsterhive123, since many users started using issues for help/feature requests instead of bug reports, I decided to open a dedicated [Discussions section](https://github.com/hashlips-lab/nft-erc721-collection/discussions). This will help me focusing on security issues and bugs while the whole community can grow and develop a strong know-how together.

Discussions will be divided in categories with different purposes and features that should fit any need, I encourage you moving this topic there if you are still interested in it. 😉

Thank you!
