### ISSUE TITLE
TailwindCSS

### ISSUE THREAD

**Issue by BobbyBorisov** [hashlips-lab/nft-erc721-collection#13]
Hey guys!

First of all i wanna thank you for the hard work! I was just trying to use the old repo of hashlips regarding minting dapp and saw that it used just regular css but when i saw here you are using tailwindcss my heart melted! Thank you! I was wondering what is the process of building the assets? do you need to run the tailwind-cli tool via npx or? I think many people will want to change the look of the minting dapp in order to be unique. i guess right now it would be easier than the last minting dapp. 

Cheers!

**Comment by liarco** [comment]
Hi @BobbyBorisov,
thank you for your feedback. I'm working on a video series covering all features available in this project. I hope I'll be able to publish the one about "DAPP customization" soon.

In the meanwhile here is a quick cheat-sheet:
- in order to build your dapp for testing, you can just install your dependencies inside the `/minting-dapp` folder using `yarn` and then run `yarn dev-server`. This is gonna spawn a background process compiling and serving your code with live refresh on any change (open your browser to `http://127.0.0.1:8080` to see it in action)
- the Tailwind config file contains some aliases for colors so you can quickly change the look-and-feel: https://github.com/hashlips-lab/nft-erc721-collection/blob/d7006cdb1ce299bdf5870fffb0e888821e5bcaa5/minting-dapp/tailwind.config.js#L11-L18
- once you are happy with your changes you can simply stop your dev server with `ctrl+c` (even on MacOS) and build your DAPP with `yarn build`. Deploy the content of the `/minting-dapp/public` folder to the root of any static web hosting and everything should work as expected

I'm gonna update this issue as soon as I publish the videos.

**Comment by BobbyBorisov** [comment]
Thank you Marco! I will try to change the design completely though! But the skinning you have done is awesome! Ciao

**Comment by gitrevo** [comment]
> Thank you Marco! I will try to change the design completely though! But the skinning you have done is awesome! Ciao

It would be nice of you to share the complete transformation of the minting-dapp page :>

**Comment by liarco** [comment]
> It would be nice of you to share the complete transformation of the minting-dapp page :>

I already planned a series of 10+ videos about this tool, one of them is DAPP look and feel customization. I just have to take the time to properly script and record all the stuff. I hope they are coming soon! 😉
