### ISSUE TITLE
Can not verify the contract on Rinkeby, is it from the network?

### ISSUE THREAD

**Issue by Whik06** [hashlips-lab/nft-erc721-collection#132]
![image](https://user-images.githubusercontent.com/87854338/158483102-4c51893f-0144-47f9-8ef4-2b396277e1eb.png)

**Comment by liarco** [comment]
Hi @Whik06, it seems like you are not using the tool in the correct way. Please follow the steps in [this video](https://www.youtube.com/watch?v=Zhmj4PiJ-GA&t=4136s). I see you have two contracts in your folder and that's not supported (unless you are doing some advanced stuff and you really know what you are doing).

I'm closing this since this is not an issue with the tool itself, but please feel free to reply if needed.
