### ISSUE TITLE
Could we have a json for the whitelisted wallets and another json for pre-sale allowed wallets?

### ISSUE THREAD

**Issue by frank-martinez-27** [hashlips-lab/nft-erc721-collection#14]
Hi,

I loved the simplicity of this library, is amazing, thank you so much!

I was wondering what would be required to also add a json file with specific wallets that can mint during the pre-sale? My use case is that I would like to start allowing partners to mint themselves for 0 ETH + Gas and then allow a few pre-sales wallets for 0.03 ETH + Gas and finally the 0.05 ETH + Gas for public.

Would this need a big change in the underlying logic?

Thank you!

**Comment by liarco** [comment]
Hi @frank-martinez-27, thank you for your feedback.

The thing you want to achieve should be already supported **as long as the addresses are not the same between the two sales**.

The whitelist sale can be open multiple times with different pricing configurations and a different root hash for the whitelist.

The steps should be the following:
- run the first whitelist as shown in our tutorials, using the "partners" configuration (0 ETH price)
- change the whitelist price to 0.03 ETH in the configuration
- change the whitelisted addresses inside the `whitelist.json` file
- run the `yarn whitelist-open` command again
- close the whitelist sale before opening the pre-sale (or public sale)

Remember that wallets from the first whitelist will not be able to mint again, that's because the [whitelistClaimed](https://github.com/hashlips-lab/nft-erc721-collection/blob/d7006cdb1ce299bdf5870fffb0e888821e5bcaa5/smart-contract/contracts/YourNftToken.sol#L19) map is the same and doesn't reset between the two sales.

I hope this helps you, I didn't have the chance to test this but I think it should work properly. It would be great if you could leave a feedback here if you have the chance to try it out.

**Comment by frank-martinez-27** [comment]
@liarco thank you for your fast response! You rock! Ill leave this ticket open to test and give some feedback on my tests :D

**Comment by frank-martinez-27** [comment]
@liarco it worked like a charm! Thank you!
