### ISSUE TITLE
limit presale quantity?

### ISSUE THREAD

**Issue by fawzydede** [hashlips-lab/nft-erc721-collection#142]
thanks for the stuffs. i'm new to this stuff and i hope i can do this by myself but i'm not. can you please guide me how to automatically pauses minting after reaching specific amount of supply like `...to.be.revertedWith('Max preSale supply exceeded!');`? to avoid wholesale then not reaching public sale for a small number of collection. sorry for my bad english hope you get the point, also sorry if this was unnecessary question. thanks in advance!

**Comment by liarco** [comment]
Hi @DedeFawzy this thing can be done, but it would require some work on both the contract and the DAPP in order to have a good UX (my main concern is: let's say you can mint 3 tokens per transaction during presale and the presale limit is `1000` while the current supply is `999`, the DAPP would allow people to try minting up to 3 tokens, but it would fail because they can mint only 1...).

Anyway I'm sorry but I don't have time to work on this kind of custom example right now... I'm gonna leave this open so maybe someone else can help (or I can get back on this if I have some time).

Thank you for your understanding!

**Comment by liarco** [comment]
Hi @fawzydede, since many users started using issues for help/feature requests instead of bug reports, I decided to open a dedicated [Discussions section](https://github.com/hashlips-lab/nft-erc721-collection/discussions). This will help me focusing on security issues and bugs while the whole community can grow and develop a strong know-how together.

Discussions will be divided in categories with different purposes and features that should fit any need, I encourage you moving this topic there if you are still interested in it. 😉

Thank you!
