### ISSUE TITLE
Replacement Fee too low

### ISSUE THREAD

**Issue by miltonisblurrd** [hashlips-lab/nft-erc721-collection#148]
hello, I had my contract verified when I first attempted the project. Now that I try it again for a second time I get this error. not sure exaxtly what I am doing wrong. 
![Screen Shot 2022-03-18 at 5 05 44 PM](https://user-images.githubusercontent.com/42359159/159098620-535b19d2-1261-4ba9-b201-2eb43f0d7849.png)

I am not using any other networks but truffle and rinkeby.

**Comment by liarco** [comment]
Hi @miltonisblurrd this issue is not related to this project, that probably has to do with MetaMask. You might have a stuck transaction or maybe your wallet is off-sync with the network. Since you are just using the testnet you might try to [reset your account](https://metamask.zendesk.com/hc/en-us/articles/360015488891-How-to-reset-your-account) (for that specific wallet).

I hope this helps, please let me know if you are able to solve the issue.

**Comment by liarco** [comment]
Closing this since I received no feedback. This issue seems related to a stuck transaction or something like that, it shouldn't be a real bug in the project.

Feel free to open another request for help in the brand new [Discussions section](https://github.com/hashlips-lab/nft-erc721-collection/discussions).
