### ISSUE TITLE
"Address already claimed" error

### ISSUE THREAD

**Issue by frank-martinez-27** [hashlips-lab/nft-erc721-collection#16]
Steps to reproduce:

- Created new wallet, added fake ETH and added the public key to the whitelist.json
- I have this configuration in `CollectionConfig.ts`

```
...
whitelistSale: {
    price: 0.00,
    maxMintAmountPerTx: 2,
  },
...
```
- Ran `yarn deploy --network rinkeby`
- Updated the contractAddress on the `CollectionConfig.ts` file
- Ran `yarn whitelist-open --network rinkeby`
- In a separate terminal ran the `minting-dapp`
- Connect the new wallet with the fake ETH
- Mint
- Confirm mint in testnets.opensea.io
- Go back to `minting-dapp` and hit the mint button again

Expected:

- You can mint a 2nd NFT

Current:
- You get `Execution reverted: Address already claimed`
<img width="525" alt="image" src="https://user-images.githubusercontent.com/32154686/154934958-693d4f2a-60c4-4e67-b597-736079e7b4a4.png">

I tried:
- Making `maxMintAmountPerTx: 3` and then ran  `yarn whitelist-open --network rinkeby`, tried to mint again through the dapp, same error

**Comment by frank-martinez-27** [comment]
Note: The `Supply: 3/1000` you see there are from the same test I did with 3 different wallets as you can see here: 
<img width="914" alt="image" src="https://user-images.githubusercontent.com/32154686/154935500-d87e06b2-00ab-4f8a-adaa-8f4e30918b85.png">

**Comment by liarco** [comment]
Hi @frank-martinez-27 thats working as intended. The whitelist sale allows people to make **one transaction per wallet only**, this is the only way to ensure people are not abusing that feature.

If you want to allow WL wallets to make more than one transaction you can do it by removing the following lines:

https://github.com/hashlips-lab/nft-erc721-collection/blob/d7006cdb1ce299bdf5870fffb0e888821e5bcaa5/smart-contract/contracts/YourNftToken.sol#L19

https://github.com/hashlips-lab/nft-erc721-collection/blob/d7006cdb1ce299bdf5870fffb0e888821e5bcaa5/smart-contract/contracts/YourNftToken.sol#L65

https://github.com/hashlips-lab/nft-erc721-collection/blob/d7006cdb1ce299bdf5870fffb0e888821e5bcaa5/smart-contract/contracts/YourNftToken.sol#L69

⚠️ But then people will be able to mint as many tokens they want during the whitelist sale and that is usually a bad thing for a collection, because then many tokens can be sold under the public mint price while still earning money so this might lower the floor price. ⚠️
