### ISSUE TITLE
DAPP Changes/Suggestions

### ISSUE THREAD

**Issue by Lypheal** [hashlips-lab/nft-erc721-collection#166]
I would like to suggest some features for the minting DAPP.
1. Adding a background (I know it's easy but most people don't know how to, so just add a line.)
2. Adding some UI effects.
3. Improving the design.
4. **Very much requested feature:** Implement the dapp into a website i.e. make a whole website. A whole website with features like _About section_, _who the owners of the projects are_ etc will help new creators a lot!

These are the features/suggestions. Feel free to reply and give comments. All these features are really requested and if you can implement them, new creators like me will be benefited A LOT and more people would like to use Hashlips' contract/dapp.

**Comment by liarco** [comment]
Hi @Lypheal,
thank you for your feedback. Some of these things are beyond the scope of this project, but I will take it into consideration when thinking about what to do for the next versions.

I'm gonna leave some considerations about the features:
1. I was thinking about adding the example [I shared here](https://github.com/hashlips-lab/nft-erc721-collection/issues/46#issuecomment-1054274405) as a comment into the SCSS
2. the DAPP is kept simple for 2 main reasons:
   1. this is an open-source and free project so the resources are limited to my free time and I must keep the DAPP simple enough in order to be able to maintain that in the future 😉
   2. adding effects might require adding much code and make it harder to customize the look & feel. The actual markup is extremely basic and people can change it completely with no need to worry about the main DAPP logic
3. keeping in mind what I said for (2), what do you mean by "improving the design"? can you give some examples?
    Please remember that purpose of this DAPP is being a good starting point (ready for unexperienced users, "easy to build on top of it" for devs), of course we can improve it, but the purpose should stay the same
4. I'm sorry but this won't probably happen (at least not anytime soon). We might create another project for a website, but it will be a separate codebase to serve a completely different purpose

I'm gonna leave this open so we can collect more feedback.

**Comment by Lypheal** [comment]
Okay!
3. By improving the design, I just meant like improving the button styles etc nothing else.

**Comment by liarco** [comment]
Hi @Lypheal, since many users started using issues for help/feature requests instead of bug reports, I decided to open a dedicated [Discussions section](https://github.com/hashlips-lab/nft-erc721-collection/discussions). This will help me focusing on security issues and bugs while the whole community can grow and develop a strong know-how together.

Discussions will be divided in categories with different purposes and features that should fit any need, I encourage you moving this topic there if you are still interested in it. 😉

Thank you!
