### ISSUE TITLE
Minting dapp to public hosting - Build index html not working

### ISSUE THREAD

**Issue by ashu223** [hashlips-lab/nft-erc721-collection#175]
I'm trying to create a minting dapp from [[minting-dapp](https://github.com/hashlips-lab/nft-erc721-collection)]. Version 2.1.1
The minting website working completely fine on test networks. When I'm trying to build the files for hosting the build index.html file does not work.
This is the error I'm getting: [[Index html Error ](https://i.ibb.co/cF8McK8/Website-Minting-dapp-error.png)]
It just shows the text "Logo" on the web page. 
Is this a bug? or I'm I missing anything?
Please help me to fix this.
Thank You.

**Comment by 0kt4y** [comment]
1

**Comment by 0kt4y** [comment]
possible mistakes are:
1) the content of "public" has been deployed to a subfolder instead of the root path (e.g. "[yourdomain.com/mint] instead of mint.youdomain.com
2) you forgot to run "yarn build" before copying the content of "public" or you had your dev server running in the background while running the build
3) you have some permission issues on your web hosting so the assets cannot be accessed properly
possible solutions by Liarco

**Comment by 0kt4y** [comment]
> I'm trying to create a minting dapp from [[minting-dapp](https://github.com/hashlips-lab/nft-erc721-collection)]. Version 2.1.1 The minting website working completely fine on test networks. When I'm trying to build the files for hosting the build index.html file does not work. This is the error I'm getting: [[Index html Error ](https://i.ibb.co/cF8McK8/Website-Minting-dapp-error.png)] It just shows the text "Logo" on the web page. Is this a bug? or I'm I missing anything? Please help me to fix this. Thank You.

possible mistakes are:

the content of "public" has been deployed to a subfolder instead of the root path (e.g. "[yourdomain.com/mint] instead of mint.youdomain.com
you forgot to run "yarn build" before copying the content of "public" or you had your dev server running in the background while running the build
you have some permission issues on your web hosting so the assets cannot be accessed properly
possible solutions by Liarco

**Comment by liarco** [comment]
Thank you @0kt4y for your help. That's correct.

**Comment by 0kt4y** [comment]
> Thank you @0kt4y for your help. That's correct.

For sure thats correct because it worked for me😬
