### ISSUE TITLE
NFT number pre reveal not showed

### ISSUE THREAD

**Issue by Salro1g** [hashlips-lab/nft-erc721-collection#187]
Hi

I post this few days ago. When I have the NFTs in not reveal, I can see the image, all ok, but all my NFTs are same, I mean that the NFTs don't show their identification number #1, #2, #3... I know that the hidden.json is a metadata same for all the collection. How can I do to resolve this? Because all collections in opensea when they are in not reveal, they show their ID.

**Comment by Salro1g** [comment]
As far I have seen, the collections not revealed have a hidden metadata specifically for every NFT, using all the same image/gif of course, but to this way you can write every name corresponding to every NFT. Is it possible with this script? I mean, instead of put in the metadata URI a single .json, if my collection has 5k nft so 5k .json for the hidden metadata.

**Comment by liarco** [comment]
Hi @Salro1g, I'm gonna be quick but feel free to ask on the HashLips' discord server for this, there you might find a dev to hire in order to get what you need.

> Because all collections in opensea when they are in not reveal, they show their ID.

This is not true actually, many collections simply have a single hidden file for every token. It's just up to the author to decide what to do here, there is no standard.

To have dedicated names for each token, you would have to change the smart contract in order to return a different token URI for each ID and then you have to generate a full set of metadata files and upload them to IPFS. As I said, I can't provide you with and example for this, but if you can't do that on your own, you may find a dev on the discord server.
