### ISSUE TITLE
Can we have "maxMintAmountPerWallet"?

### ISSUE THREAD

**Issue by frank-martinez-27** [hashlips-lab/nft-erc721-collection#19]
In my ignorance I have previously misunderstood "maxMintAmountPerTx" with "maxMintAmountPerWallet", but is there any way to have this feature to limit the amount of times a user comes to our dapp to mint?

**Comment by liarco** [comment]
Hi @frank-martinez-27, don't worry, that's fine. Unfortunately there is no way to really enforce a limit "per person" (which is what people is usually looking for). That's because any check you can put in place can be simply avoided by transferring the tokens after mint (in case the contract checks the account balance) or by controlling multiple addresses at the same time.

Since claiming that there will be a limit per wallet/person is essentially a fake statement, we are not encouraging any solution in this direction. The only thing thing that goes near to this (to my knowledge) is our whitelist implementation, because that sale is not public, so you can try to avoid accepting addresses that may be connected to the same person.

I hope this helps.

**Comment by frank-martinez-27** [comment]
@liarco you rock, thank you :D

**Comment by thepeanutgalleryandco** [comment]
@liarco what if you guys add a maxMintAmountPerWLWallet and then track that maybe via an array of some sort on the contract so that it can be enforced?

**Comment by liarco** [comment]
> @liarco what if you guys add a maxMintAmountPerWLWallet and then track that maybe via an array of some sort on the contract so that it can be enforced?

Hi @thepeanutgalleryandco, thank you for your suggestion. Unfortunately that would only work for the whitelist sale, not the public ones.

Also (but this is just a matter of taste) I think that a whitelist spot should be seen like a "ticket for a single ride". Having too many tokens minted at a lower price compared to the public sale is not good for the token's economy, because many people would then be able to list for under the sale price and minting would be discouraged.
IMHO a proper whitelist spot should allow for 1 TX and 1 token, so people have the chance to mint at a lower price, but if they decide to sell below mint price then they are losing their advantage over other holders. That's why we also provide with an optional pre-sale before the public sale... the whitelist should be very exclusive.

Of course, everyone can choose it's own "rules of the game", but here is what I would probably do for my own collection if I had to start one today:
- 3-10k max supply (depending on the type of project)
- 5-10% whitelist spots with a 20% discount over the public sale price (1TX per address, 1 token per TX)
- timed pre-sale with a 10% discount over the public sale price (this should be very quick, depending on the community size, maybe 2 rounds of 1 hour each to fit different timezones)
- public sale until sold-out
- do what's on the roadmap (it may sound obvious but, you know, better specify 😜)
