### ISSUE TITLE
Opensea properties are showing "new trait" instead of percentages% under attributes section of my each item

### ISSUE THREAD

**Issue by dcryptodev** [hashlips-lab/nft-erc721-collection#197]
Hi all my openSea testnet (polygon Mumbai) is showing "new traits" where it should show the percentage % of the attribute.

Also the properties tabs are not coming up on the collection beside the filter bar.  

Does anyone know why this is happening? 

Does anyone know what needs to be done to resolve this?

@liarco @Jonas-Lieske or anyone would be great to get your support here.

**Comment by Angrywolvesdev** [comment]
The same thing happens to me, maybe I just need to wait for OpenSea to update that data

**Comment by dcryptodev** [comment]
I've waiting for 3 days now @Angrywolvesdev

**Comment by dcryptodev** [comment]
Does anyone have a solution to this issue?

**Comment by liarco** [comment]
@dcryptodev please avoid tagging people this way, this fills our e-mail with spam and you won't get answers any faster. Thank you.

About the issue, sometimes this took up to 7 days on the test version of OpenSea (on rinkeby, polygon can be even slower). That's something that depends on OpenSea, we can't do anything about it.

**Comment by aliimashli** [comment]
@dcryptodev hi, sorry bothering you. did you solve this issue? my properties also show new traits or wrong percentage on polygon on opensea.

**Comment by Angrywolvesdev** [comment]
I don't know ga solved?  maybe @liarco can help

**Comment by liarco** [comment]
Hi @aliimashli and @Angrywolvesdev,
this issue should have nothing to do with this project since it depends on your metadata and on OpenSea's indexing system (the contract doesn't make any difference here, especially if you see the trait names on the website, that means that OpenSea is fetching the data from the contract correctly).

My suggestion is to reach out to OpenSea directly on their Discord server.
