### ISSUE TITLE
maximum supply

### ISSUE THREAD

**Issue by Angrywolvesdev** [hashlips-lab/nft-erc721-collection#198]
Hi, a quick question. If I want to create in the first part 5000 Nft and then in a second part raise another 5000 in the maximum amount of the contract I can put 5000 and then edit that number to 10,000 or should I write 10,000 at once.

**Comment by liarco** [comment]
Hi @Angrywolvesdev, this project doesn't support updating the supply after deployment. Leaving that value as dynamic can be seen as a lack of transparency from the users because the collection owner would then be able to change the supply randomly.

That said, there are some possible solutions is you still want to implement it, I probably gave some advice to people asking the same thing so you can try using the search tool in the Issues page. You can also ask on the HashLips' discord server, you might find a dev that can help you.

**Comment by Angrywolvesdev** [comment]
So what would happen if I put 10,000 but I only have 5,000 images created, because I would like to divide the project into two parts and once the first one is sold, publish the second. in the same contract it is possible?

**Comment by liarco** [comment]
That's absolutely possible, but you have to customize the project (probably both the contract and DAPP) in order to support this custom behavior. This is not supported out-of-the-box and unfortunately I don't have any ready example on how to do it.
