### ISSUE TITLE
Dapp command issues or maybe requests?

### ISSUE THREAD

**Issue by cryptocraig-nft** [hashlips-lab/nft-erc721-collection#199]
Hi @liarco & @hashlips, 

Thanks for all your hard work, I had no experience what so ever before taking on this project and without you guys I guess it wouldn't be happening, so thanks again!

My issues are:  
I set the whitelist to have a max mint amount of 1. I then I minted the nft and closed the white list. I then changed the max mint amount to 2, hoping to be able to mint another nft but the dapp doesn't allow this, as I have previously minted. I did also run 'yarn build' in the minting-dapp file before trying to mint again. Is there a way to do this? I was hoping to run multiple whitelists.

Is there a way to reveal just the minted nft's, rather than the whole collection?

Is there a way to make the whole collection visible on opensea? Is this called lazy minting?

Also the nft I minted showed in opensea but with no 'hidden' image this was like this for about 24hours. I have now revealed the collection, its still not showing an image but shows the description. its now been about 2hours. can opensea just take this long to fetch the data or is it likely I have don something wrong?

Sorry for all the questions, if you guys or anyone else can help it would be so very much appreciated.

Thanks

**Comment by liarco** [comment]
Hi @cryptocraig-nft, I'm happy to answer these questions but I want to let you know that today I opened the Discussions section on GitHub and it can be used for this kind of questions 😉

> I set the whitelist to have a max mint amount of 1. I then I minted the nft and closed the white list. I then changed the max mint amount to 2, hoping to be able to mint another nft but the dapp doesn't allow this, as I have previously minted. I did also run 'yarn build' in the minting-dapp file before trying to mint again. Is there a way to do this? I was hoping to run multiple whitelists.

Resetting the whitelist state would cost a huge amount of gas so we can't implement that. You might create a fully custom implementation for that, but I don't think this will be added to our project anytime soon.

The current whitelist implementation has the following rules:
1. each address will be able to use the `whitelistMint()` function only once
2. you can run multiple whitelist sales, but with different addresses (because the "whitelist has minted" state can't be reset globally)

> Is there a way to reveal just the minted nft's, rather than the whole collection?

We have a dedicated solution for this, it's the [Safe NFT Metadata Provider](https://github.com/hashlips-lab/safe-nft-metadata-provider).

> Is there a way to make the whole collection visible on opensea? Is this called lazy minting?

With a contract you can mint all tokens to the owner address and then list them on OpenSea, but unless you decide to list all tokens manually, you will have to request an API key to the OpenSea team and create a script to batch list all tokens using their API.

> Also the nft I minted showed in opensea but with no 'hidden' image this was like this for about 24hours. I have now revealed the collection, its still not showing an image but shows the description. its now been about 2hours. can opensea just take this long to fetch the data or is it likely I have don something wrong?

OpenSea might be slow updating stuff, but you should make sure [your metadata is valid](https://docs.opensea.io/docs/4-debugging-your-metadata) (some users found out that the problem was a trailing comma in their metadata files).

**Comment by cryptocraig-nft** [comment]
Thanks for the help, much appreciated!
