### ISSUE TITLE
Tokens not appearing in OpenSea

### ISSUE THREAD

**Issue by Angrywolvesdev** [hashlips-lab/nft-erc721-collection#200]
Did it happen to someone else? NFTs do not appear in the account after minting on the polygon chain. In the test network it works perfectly but in the real one it does not

**Comment by FrancoGedor** [comment]
Happened to me with Polygon as well.

**Comment by Angrywolvesdev** [comment]
Yes, did you solve it?

**Comment by dcryptodev** [comment]
Yes it happened to me on the test network of Opensea with the Mumabi smart contract. I minted 16 NFTs out of 30. The first everything showed up instead of number 1,3,5,11 only 13 were showing up on Opensea. 

I used the Opensea Api validator to check if opensea was retrieving that collection it was coming up as {success:false} for the specific missing NFT's.
e.g. the minted NFT: 
https://testnets-api.opensea.io/asset/mumbai/SMART_CONTRACT_ADDRESS/3/validate - Returned:
{ success: false }

I'm not sure why Opensea is having this issue. But I know my NFT's for 1,3,5, and 11 were minted for sure cause it shows that on my smart contract! I also waited for a few days hoping for this to be resolve itself but nothing changed.

Does anyone know how we can resolve this issue or force an update opensea for the NFT's that are not showing up inside the collection of opensea?

**Comment by Angrywolvesdev** [comment]
It seems that the error is very common in the Polygon chain, I tried to mint the collection twice and still they do not appear in OpenSea, only if the quantity is small, maybe with 1 to 1 if they load.

**Comment by liarco** [comment]
Hi everyone, OpenSea is well known to be very slow updating data, especially for high token counts (and also with Polygon, so having them both is not a great combo). The only thing I'm pretty sure about is that this is not an issue with our code, so I'm gonna close this and I suggest you moving the discussion to the [Discussions section](https://github.com/hashlips-lab/nft-erc721-collection/discussions) that I just opened.

From now on, issues will be used for reporting bugs only. Thank you for your understanding! 😉
