### ISSUE TITLE
Question about reveal

### ISSUE THREAD

**Issue by rawkfist2022** [hashlips-lab/nft-erc721-collection#202]
Is there a way to have the reveal process only work for mints that are no longer owned by the creator? Once the reveal process is run, then anyone can update the metadata on Opensea and see the attributes.  I'd like for this to be hidden until they buy it from my collection. I wish I could even try to write this type of code, but my knowledge is very limited. Thanks!

**Comment by liarco** [comment]
Hi @rawkfist2022 this cannot be achieved on-chain.
You can only do that using an external API instead of IPFS, but this requires a dedicated back end solution.

I recently enabled GitHub Discussions so you might use that tool in order to ask questions or discuss general topics instead of using issues. Thank you! 😉

**Comment by rawkfist2022** [comment]
Sorry about that. I was looking for somewhere to ask that question, but didn't see that. 
Thanks!

**Comment by liarco** [comment]
@rawkfist2022 no problem at all, I enabled it after you opened the issue! I just wanted to let you know 😉
