### ISSUE TITLE
How to use this on polygon network?

### ISSUE THREAD

**Issue by explorion** [hashlips-lab/nft-erc721-collection#21]
Hey @liarco,

First of all, thank you man! this repository is just dope!!! <3

How can we use this on polygon network?

Can you please, also show how to customise the Dapp as well

Thank you so much
Take care

**Comment by liarco** [comment]
Hi @explorion, thank you for your feedback!

My experience is mainly on the ETH chain, so before giving any advice I need to do proper testing for this and it's absolutely something I want to address.

I'm gonna get back to you asap.

**Comment by explorion** [comment]
Super cool @liarco 
eagerly waiting for more videos from you soon!

**Comment by wwwguy** [comment]
Great stuff! Likewise though... it would be much much greater if there was a way to adjust the .env variables to allow for use on Polygon mainnet and Mumbai testnet. The prohibitive gas costs of ETH make the majority of NFT use cases non viable as you know (which is why many of the other HashLips videos contain explanations for deploying with Polygon). This repository is sooooo good having combined several of the key/common projects one would want all into one explanation! Unfortunately as it's hardcoded for ETH it's very limiting. Great job though... hoping you can push an updated version that would allow other networks.

**Comment by liarco** [comment]
Hi @wwwguy, thank you for your feedback!

I agree with you, but this is project needs a lot of maintenance and I need to focus the efforts on what I can do better. At the moment there are higher priorities so I can't work on this feature immediately, but I would be more than happy if someone from the community could contribute with some examples, or even a PR with an implementation proposal for this feature. 😉

**Comment by wwwguy** [comment]
> Hi @wwwguy, thank you for your feedback!
> 
> I agree with you, but this is project needs a lot of maintenance and I need to focus the efforts on what I can do better. At the moment there are higher priorities so I can't work on this feature immediately, but I would be more than happy if someone from the community could contribute with some examples, or even a PR with an implementation proposal for this feature. 😉

Appreciate you brother!! 😉

**Comment by bensonmunyan** [comment]
100% would LOVE to see Polygon compatibility.

**Comment by Berenike29** [comment]
Excited to be able to use this on Polygon. Thank you for all your work, literally would be lost without all the Hashlips resources. Any idea when a patch might be ready to deploy to Polygon? I'm happy to help test if needed. :)

**Comment by liarco** [comment]
Closing this. Polygon support is available since version `2.1.0` (thanks to #57). Thanks to anyone who contributed to this.
