### ISSUE TITLE
.env // How to fill it out correctly?

### ISSUE THREAD

**Issue by volkovecom** [hashlips-lab/nft-erc721-collection#25]
Dear @liarco 

I did not understand well from the video how to fill in the **.env** file

Please explain which variables need to be changed?

I understood what needs to be written in the **COLLECTION_URI_PREFIX** variable.

But I didn't figure out how to fill out the rest correctly.

Please help me figure out how to fill out the file correctly! (hope this helps someone)

**COLLECTION_URI_PREFIX**=?(where to get it?)

**NETWORK_RINKEBY_URL**=?(where to get it?)
**NETWORK_RINKEBY_PRIVATE_KEY**=?(where to get it?)

**NETWORK_MAINNET_URL**=?(where to get it?)
**NETWORK_MAINNET_PRIVATE_KEY**=?(where to get it?)

**GAS_REPORTER_COIN_MARKET_CAP_API_KEY**=?(where to get it?)

**ETHERSCAN_API_KEY**=?(where to get it?)

Thank you!

**Comment by volkovecom** [comment]
Omg

I've dealt with them: COLLECTION_URI_PREFIX, NETWORK_RINKEBY_URL, NETWORK_RINKEBY_PRIVATE_KEY, ETHERSCAN_API_KEY

But I haven't figured out what to do with it yet: 

![image](https://user-images.githubusercontent.com/53946921/155419495-acacbff9-b910-47a6-bb86-1b245678cc56.png)

Thank you!

**Comment by liarco** [comment]
Hi @volkovecom, did you watch my "speedrun" video? I'm gonna go into details in te next videos from that series, in the meanwhile you should find further information in this [video from HashLips](https://youtu.be/ynZzPNkS1nk) which follows my same steps while explaining them.

Let me know if this helps.

> But I haven't figured out what to do with it yet:
> 
> ![image](https://user-images.githubusercontent.com/53946921/155419495-acacbff9-b910-47a6-bb86-1b245678cc56.png)

About these latest variables:
- `NETWORK_MAINNET_URL` and `NETWORK_MAINNET_PRIVATE_KEY` are the same as the `RINKEBY` version, but that configuration is used for the main ETH network (e.g. `yarn deploy --network mainnet`)
- the API key from CoinMarketCap is used in order to estimate gas fees, I'm gonna publish a video about this topic, but basically it's used when running `yarn test-gas`, this command runs tests on your contract and gives you a report about gas fees. If you add that API key you are also gonna get the price in USD using the current ETH price from CoinMarketCap

**Comment by volkovecom** [comment]
@liarco Thank you! That helped me figure it out!
