### ISSUE TITLE
Can't mint with ledger even if "Blind signing" is enabled

### ISSUE THREAD

**Issue by niccolofanton** [hashlips-lab/nft-erc721-collection#274]
Hi, first of all, thanks for your amazing work.

I have an issue with the minting dApp, if a user tries to mint with a ledger it throws the following error: `Please enable Blind signing or Contract data in the Ethereum app Settings`

The problem is that I've already done that and I can mint from other minting dApps without this issue, any suggestions?

Thanks

```
MetaMask - RPC Error: Please enable Blind signing or Contract data in the Ethereum app Settings
code: -32603
message: "Please enable Blind signing or Contract data in the Ethereum app Settings"
```

**Comment by niccolofanton** [comment]
Update: if found the problem!

I renamed the `mint` function to `mintPublic` and it worked like a charm with my hardware wallet.

I've found a comment on reddit with this suggestion 
<img width="743" alt="Schermata 2022-05-08 alle 17 56 02" src="https://user-images.githubusercontent.com/16043681/167304395-b934ae9e-78c8-437f-99ac-b58568a8a779.png">

**Comment by liarco** [comment]
Hi @niccolofanton I'm sorry but this bug report is not valid since you are not providing us with all the required information.

Btw this doesn't seem to be a bug at all and your solution appears to be wrong. Please read the following information because you should be able to run this project without any customization.

In order to properly use your HW wallet with MetaMask you have to enable multiple options ([blind signing](https://support.ledger.com/hc/en-us/articles/4405481324433-Enable-blind-signing-in-the-Ethereum-ETH-app?docs=true) alone is not enough). I'm not sure if that's required in order to provide you with additional information before you actually accept the transaction (as an additional security measure) or for some other reason, but I've always been able to use HW wallets without any custom code just by enabling the following options inside my Ledger app:
1) Blind signing: `enabled` (required)
    This will allow MetaMask to request signatures of transactions that interact with contracts.
    ⚠️ Please read the [official docs](https://support.ledger.com/hc/en-us/articles/4405481324433-Enable-blind-signing-in-the-Ethereum-ETH-app?docs=true) and always disable this option after use ⚠️
    ![IMG_1987](https://user-images.githubusercontent.com/1532277/167310733-419b7faa-ab03-439e-9cf8-07e8384d6924.jpg)
2) Debug data: `enabled` (required)
    This option shows additional information about the transaction so you can understand a bit more of what's going on. MetaMask won't be able to sign the transaction successfully without this.
    ![IMG_1988](https://user-images.githubusercontent.com/1532277/167310755-99141fe1-ab73-4c9a-91d5-e44e6782e6a9.jpg) 
3) Nonce: `not enabled` (optional)
    This option will show the nonce value as an additional information to be validated. It might be useful, but it's not strictly required.
    ![IMG_1989](https://user-images.githubusercontent.com/1532277/167310855-419ad518-c9b5-48dd-90c8-c34d055e9fda.jpg)

**Comment by pentcle** [comment]
> Update: if found the problem!
> 
> I renamed the `mint` function to `mintPublic` and it worked like a charm with my hardware wallet.
> 
> I've found a comment on reddit with this suggestion <img alt="Schermata 2022-05-08 alle 17 56 02" width="743" src="https://user-images.githubusercontent.com/16043681/167304395-b934ae9e-78c8-437f-99ac-b58568a8a779.png">

have you got the link to the reddit comment?
