### ISSUE TITLE
pre-Reveal titles of each NFT do not have token ID

### ISSUE THREAD

**Issue by waldehj** [hashlips-lab/nft-erc721-collection#279]
When the contract is in it's pre-reveal state all NFTs are just the collection name with no token ID shown. Currently working on adding functionality so the hidden metadata gives each NFT it's token ID pre-reveal. 'Collection Name #1, #2, #3' etc.

**Comment by wflieller** [comment]
It should show you the token ID in the metadata section on Opensea even pre-reveal no?

**Comment by liarco** [comment]
Hi, please use issues for bug reports only and provide the requested information. Otherwise you may use the Discussions section which might be a perfect fit for this topic.

Just as a quick answer: showing different metadata for hidden tokens is not mandatory. Many collections do it, many others don't. If you really need that you would have to produce dedicated JSON files for each hidden token and upload them to IPFS, then you would have to amend the contract code to return different URIs for each hidden token.
Our contract doesn't support that since we don't see it as an extremely valuable feature, but it's a matter of taste.
