### ISSUE TITLE
Minting Dapp

### ISSUE THREAD

**Issue by Catzskull** [hashlips-lab/nft-erc721-collection#299]
I keep on getting that error what should i do?
$ encore dev-server
Running webpack-dev-server ...

/Users/jonathanseverin/Downloads/nft-erc721-collection-2.3.0/minting-dapp/node_modules/webpack-dev-server/lib/Server.js:2432
        throw error;
        ^

Error: listen EADDRINUSE: address already in use 127.0.0.1:8080
    at Server.setupListenHandle [as _listen2] (node:net:1330:16)
    at listenInCluster (node:net:1378:12)
    at GetAddrInfoReqWrap.doListen [as callback] (node:net:1516:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:73:8) {
  code: 'EADDRINUSE',
  errno: -48,
  syscall: 'listen',
  address: '127.0.0.1',
  port: 8080
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
jonathanseverin@iMac minting-dapp %

**Comment by liarco** [comment]
Hi @Catzskull,
Issues are for bug reports only and you should include all the requested information. If you are looking for support please use the [Discussions Section](https://github.com/hashlips-lab/nft-erc721-collection/discussions) in order to get support from other community members.

In this case, the error already tells you what the problem is: `EADDRINUSE: address already in use 127.0.0.1:8080` so you already have a process running on port `8080` on your machine. You should close the other process or pick another port with the `--port 8081` when running the dev server. This error could also be found by searching old issues, so please use the search tool before opening new reports.

Thank you for your understanding.
