### ISSUE TITLE
Hidden Metadata

### ISSUE THREAD

**Issue by VeriumNFT** [hashlips-lab/nft-erc721-collection#30]
Hello @liarco

Does this repo include the safe-nft-metadata-provider to revealing metadata only for minted NFTs? Or is it currently setup up for hiding the entire collection and then revealing it using a cmd?

**Comment by liarco** [comment]
Hi @VeriumNFT,
this and the [Safe NFT metadata provider](https://github.com/hashlips-lab/safe-nft-metadata-provider) are two separate tools that you can use in combination depending on your needs. If you plan to reveal your collection during the mint stage then you should probably use the metadata provider, otherwise it's not required for your collection to work properly.

I hope this helps, feel free to ask if you have any other question.
