### ISSUE TITLE
Execution reverted: Invalid proof!

### ISSUE THREAD

**Issue by nftkk** [hashlips-lab/nft-erc721-collection#304]
Hello Guys
i did test everything before. all was fine. but now i have a big problem. whitelist sale is open now, but i cant mint. it shows me a bug:

Execution reverted: Invalid proof!

![image](https://user-images.githubusercontent.com/101070031/171063157-fab9b482-7751-4373-9253-14c073121e05.png)

I have no idea what to do right now :/

**Comment by nftkk** [comment]
on local server it works perfect, but not on public :/

**Comment by Pompeius267** [comment]
I had the same problem. Close the Whitelist (yarn whitelist-close --network truffle) and then reopen your Whitelist (yarn whitelist-open --network truffle).

**Comment by liarco** [comment]
Hi @nftkk issues should be used to report bugs so I ask you to always provide the requested information or the issue will be marked ad invalid and closed.

That said, in this case, please make sure you always rebuild your dApp and upload it again to your host every time you make any change to the `whitelist.json` file. Also, the merkle tree root hash must be updated on the contract... but I think you already did that since you said it's working in your local environment.
