### ISSUE TITLE
why there is red line under override in contract?

### ISSUE THREAD

**Issue by theartistcat** [hashlips-lab/nft-erc721-collection#312]
[](url
<img width="873" alt="Screen Shot 2022-06-08 at 2 33 40 AM" src="https://user-images.githubusercontent.com/90352279/172549099-985e7e9f-373d-428e-a33f-43e7a0be6c68.png">
)

**Comment by liarco** [comment]
@theartistcat please follow the instructions when opening issues and add all the information required to help us having a better understanding of the context.

Anyway thank you for reporting this. It looks like that's an error of the VSCode Solidity extension, maybe due to the fact it's using the wrong compiler version when linting the code.
Adding an explicit override there (as requested by the extension) leads to a compilation error.

I'm gonna see if there's any way to configure the extension so it uses the correct compiler version in order to avoid confusion.

**Comment by liarco** [comment]
Hi @theartistcat I'm testing #313 as a fix to this, may you please test the fix by applying the following change in your repo and tell me if it stops complaining about the issue?

Here is the change to apply: https://github.com/hashlips-lab/nft-erc721-collection/pull/313/files

Basically you have to add the following line to your `.vscode/settings.json` inside the project:
```json
...
  "solidity.compileUsingRemoteVersion": "0.8.9",
...
```

Thank you very much.

**Comment by theartistcat** [comment]
It works. It stops complaining about the issue. Thank you so much.
