### ISSUE TITLE
dapp bug? Issue when deploying

### ISSUE THREAD

**Issue by ericrainford** [hashlips-lab/nft-erc721-collection#324]
I can't tell if I have found a bug or am doing something wrong, I have followed the hashlips masterclass step by step and have had everything work fine but when i try deploying my dapp on vercel, netlify, or cloudfare, I get a blank page with a "Logo" text in the corner, any suggestions?

**Comment by admiralPyku** [comment]
create a copy of index.html in the build folder and update the links

**Comment by liarco** [comment]
Hi @ericrainford,
first of all, please provide all the requested information when opening a bug report, otherwise I must close the issue as invalid. If it's just a simple question, you should use the "Discussions section" and not the Issues. Also, please search for the issue before opening a new one, in this case I guess you are not deploying the dApp correctly.

Here are some search results for `blank page`: https://github.com/hashlips-lab/nft-erc721-collection/issues?q=blank+page
Here are my video tutorials, I made one on dApp deployment: https://github.com/hashlips-lab/nft-erc721-collection#youtube-tutorials

@admiralPyku thank you for helping out, but unfortunately your solution is not correct and might lead to other issues. Please avoid making manual changes to URLs, that should work out of the box if you do everything correctly. 😉
