### ISSUE TITLE
error Command failed with exit code 1 when opening whitelist

### ISSUE THREAD

**Issue by Goanft** [hashlips-lab/nft-erc721-collection#334]
Hi, i am trying to find a solution to an error i faced while trying to open up whitelist. Please advise. 
![Screenshot 2022-06-20 at 9 54 57 PM](https://user-images.githubusercontent.com/107839585/174634221-2c34e9e4-9c86-4676-8fcd-dbfb23d98219.png)

**Comment by liarco** [comment]
Hi @Goanft,
A bug report **must** follow the given template and you have to provide all the requested information, otherwise it's invalid.

If you simply wanna ask a question, you can do that in the [Discussions Section](https://github.com/hashlips-lab/nft-erc721-collection/discussions).

Thank you.
