### ISSUE TITLE
Issue about error after command yarn dev-server "Cannot find module '../../../../smart-contract/typechain/index' or its corresponding type declarations"

### ISSUE THREAD

**Issue by Tkareder** [hashlips-lab/nft-erc721-collection#337]
Hello,
I have a question about **error, appearing when i'm trying to launch next command**: 
\nft-erc721-collection-2.4.1\minting-dapp> yarn dev-server

**Response:**
 ERROR  Failed to compile with 1 errors            00:18:16
 error  in C:\nft-erc721-collection-2.4.1\minting-dapp\src\scripts\lib\NftContractType.ts          00:18:16

[tsl] ERROR in C:\nft-erc721-collection-2.4.1\minting-dapp\src\scripts\lib\NftContractType.ts(5,49)
      TS2307: Cannot find module '../../../../smart-contract/typechain/index' or its corresponding type declarations. 

Entrypoint main [big] 7.57 MiB = main.css 89.7 KiB main.js 
7.48 MiB
Entrypoint _tmp_copy (127 KiB) = 3 auxiliary assets        
webpack compiled with 1 error
 ERROR  Failed to compile with 1 errors            00:18:18
 error  in C:\nft-erc721-collection-2.4.1\minting-dapp\src\scripts\lib\NftContractType.ts          00:18:18

[tsl] ERROR in C:\nft-erc721-collection-2.4.1\minting-dapp\src\scripts\lib\NftContractType.ts(5,49)
      TS2307: Cannot find module '../../../../smart-contract/typechain/index' or its corresponding type declarations. 

Entrypoint main [big] 7.57 MiB = main.css 89.7 KiB main.js 
7.48 MiB main.a097f456b6f32bfe8e6d.hot-update.js 2.17 KiB  
Entrypoint _tmp_copy 794 bytes (127 KiB) = _tmp_copy.a097f456b6f32bfe8e6d.hot-update.js 3 auxiliary assets
webpack compiled with 1 error

**Environment** - windows 10, latest versions of all the involved frameworks.

**How can i solve this issue?**

Thanks a lot.

**Comment by Freska98** [comment]
Have the same Issue

**Comment by Freska98** [comment]
@liarco I have the same issue.

**Comment by liarco** [comment]
Hi @Tkareder, please stick to the Issue template that we provided, without that information in that exact format I must close the issue as invalid. If you just wan't to ask questions, then you should use the [Discussions Section](https://github.com/hashlips-lab/nft-erc721-collection/discussions).

Anyway, looking at the error, it seems like you are trying the run the dApp without compiling the contract. I suggest watching the tutorials in the [README](https://github.com/hashlips-lab/nft-erc721-collection#youtube-tutorials) file (please skip the "speedrun" since it's using version `1.x` so it might be confusing).

@Freska98 I hope this helps you as well.
