### ISSUE TITLE
Dapp // Link Error "Etherscan" Home Page

### ISSUE THREAD

**Issue by volkovecom** [hashlips-lab/nft-erc721-collection#34]
Hi @liarco 

I took the test all the way to the end

But I noticed that there is a problem with the "Etherscan" link on the main screen (Home Page). 

![Image 3](https://user-images.githubusercontent.com/53946921/155660076-53c31c21-26ea-4992-903b-7dc0f3fdf1df.png)

It's not directing me to my contract address. Instead, it takes me to the address: https://etherscan.io/address/0xff3d6907628538640e4950d2283956191646cf0e

How can I refer to my contract?

Thank you!

**Comment by volkovecom** [comment]
And it's the same here:

![photo_2022-02-25_09-17-07](https://user-images.githubusercontent.com/53946921/155664624-7898f552-728d-4a38-beea-010010c1b5f8.jpg)

The link leads to: https://etherscan.io/address/0xff3d6907628538640e4950d2283956191646cf0e

*This is after I successfully deployed the contract (rinkeby), ran the test all the way through (as in the video) and built the dapp, placed it on the server

**Comment by liarco** [comment]
Hi @volkovecom, the code generating the etherscan URL is using the mainnet no matter what the network is since those links become relevant just when you actually release the collection.

I'm gonna check out if I can manage to support both mainnet and rinkeby to avoid confusion, but for now you should just add `rinkeby.` to the domain manually after opening the link on your browser.

**Comment by volkovecom** [comment]
@liarco 

So if I deploy a contract in the "mainnet" network, the links will work correctly?

Right?

Thank you

**Comment by liarco** [comment]
@volkovecom yes, they actually already have the correct path, it's just the domain name that is always pointing to the mainnet.

So if you turn this:
`https://etherscan.io/address/0xff3d6907628538640e4950d2283956191646cf0e`

Into this:
`https://rinkeby.etherscan.io/address/0xff3d6907628538640e4950d2283956191646cf0e`

You get to your contract. Can you confirm that?

**Comment by volkovecom** [comment]
Excuse me! Bear with me. I did not understand well what needs to be done to make everything work correctly. Do I need to change the code or just what is shown in the video?

If I deploy a contract on the mainet network, will the Etherscan links in the greeting direct the user to my contract?

![Image 1](https://user-images.githubusercontent.com/53946921/155851102-bc041a4c-793e-440a-a9ae-3e706df125ca.png)

**Comment by volkovecom** [comment]
Now if I do this on the test network, the link to the contract works correctly when I connect to the wallet (Rinkeby)

![Image 2](https://user-images.githubusercontent.com/53946921/155851285-2bda6767-db63-48c4-9560-c7c004ec4bb3.png)

But if you don't connect the wallet, the link: https://etherscan.io/address/0xff3d6907628538640e4950d2283956191646cf0e

I just want to make sure everything is working properly before I deploy the contract on the main network.

Thank you!

**Comment by liarco** [comment]
Hi @volkovecom,
Your concern is absolutely legitimate.
The reason why you see those inconsistencies is simple: in order to keep the configuration to the minimum, we infer the current network using the web3 provider. When a user connects his wallet, we can have proper network detection so we can point any link to the correct domain (e.g. `rinkeby.etherscan.io`), but when the wallet is not connected the DAPP has no clue about which network it's supposed to be using, so all links always point to the mainnet version as a fallback.

By doing this we can ensure that the DAPP will work when deployed for a real collection without changing anything. The only other option would be having a configuration value which tells the DAPP which network to use, but then if you forget to change it from `rinkeby` to the `mainnet` you would end up with a broken deployment.

I hope this makes sense... I know this might sound confusing, but if you have any suggestions for a better approach I would be happy to hear that. 😉

**Comment by volkovecom** [comment]
@liarco Thank you. I got it. You are an amazing developer!

This can be a little confusing for users before they connect the wallet. We tell them that they can do it through Etherscan.
But by clicking on the link they will not get to our contract and will be confused.

Maybe just don't say it until the user is connected to the wallet?

![image](https://user-images.githubusercontent.com/53946921/155855308-a84c2635-f8f5-4650-b972-a56c8d20bfb4.png)

**Comment by liarco** [comment]
Sorry @volkovecom but I'm afraid I'm missing something here, so please forgive me if I'm about to repeat myself.

The links you highlighted in the screenshots are what the users see when they:
1. visit the DAPP without having MetaMask installed/enabled (the one at the top)
2. anytime, in any case (the safety notice at the bottom)

As I said, those links are broken **during tests on networks other than the Mainnet** until you connect your wallet, because the DAPP doesn't have any clue about which network you actually deployed your contract to.
So I decided to leave the Mainnet link as a fallback, so when you deploy to the Mainnet (which is the real thing) everything always works as expected since the fallback is correct in that case.

To put it in other words, the fact that links update once you connect your wallet (even if you are using a network other than the Mainnet) is just an additional feature to improve the development experience, because otherwise you would have all broken links during development and good ones in production.

To wrap up:

| Network used | Etherscan domain (wallet not connected) | Etherscan domain (wallet connected) |
| - | - | - |
| Rinkeby | www.etherscan.io | rinkeby.etherscan.io |
| Mainnet | www.etherscan.io | www.etherscan.io |

So if you deploy to the Mainnet all links should work as expected.

**Comment by volkovecom** [comment]
thank you @liarco
