### ISSUE TITLE
yarn deploy --network rinkeby EROR

### ISSUE THREAD

**Issue by DetectMR** [hashlips-lab/nft-erc721-collection#342]
Error HH8: There's one or more errors in your config file:

  * Invalid account: #0 for network: testnet - private key too short, expected 32 bytes
  * Invalid account: #0 for network: mainnet - private key too short, expected 32 bytes
  
To learn more about Hardhat's configuration, please go to https://hardhat.org/config/

**Comment by liarco** [comment]
Hi @DetectMR,
I'm sorry but this issue is invalid since it's missing all the requested information.

The first error means that you have a bad configuration in your `.env` file (you should enter your private key or remove the variable, you can't leave it empty). The second error means that you are using an outdated command: `--network rinkeby` worked with version `1.x`, from `2.x` it's `--network testnet`.

If you have any question, please use the [Discussions Section](https://github.com/hashlips-lab/nft-erc721-collection/discussions) to get support from the community.
