### ISSUE TITLE
hidden metadata not showing on opensea

### ISSUE THREAD

**Issue by rxxddy** [hashlips-lab/nft-erc721-collection#353]
the picture from the hidden metadata is not displayed on opensea, I checked absolutely everything, CID is correct, after the revival - pictures are displayed

**Comment by liarco** [comment]
Hi @rxxddy,
Im sorry but an issue must contain all the requested information and must be related to a bug otherwise it's invalid.

In this case I guess this is probably a misconfiguration or a bad formatting in the hidden metadata JSON file, so the [Discussions section](https://github.com/hashlips-lab/nft-erc721-collection/discussions) might be a better place for this.

Thanks for your understanding.
