### ISSUE TITLE
How to handle deploying from terminal while using a hardware wallet?

### ISSUE THREAD

**Issue by joven1555** [hashlips-lab/nft-erc721-collection#36]
Since deploying from terminal requires private keys, and using a hardware wallet is essential for security, is there any best practice here?

If deploying from a hardware wallet, particularly a ledger, we have to go outside of Ledger's software to get the keys to input.  Alternative would be to implement from a hot wallet, then transfer ownership after everything is setup.  But that would prevent future management from the terminal.

If we're more comfortable deploying from Remix and managing from Etherscan (since no private keys need to be input), will that still work OK or would you anticipate we'll run into issues?

Note: EXTREMELY EXCITED for the 721A update, can't wait!

**Comment by liarco** [comment]
Hi @joven1555,
using hardware wallets with Hardhat is actually possible (but I still didn't have the chance to test it and there is no plan for supporting it at the moment).

Personally I don't see much need for that in most cases, creating a dedicated MetaMask account (not wallet) for contracts deployment/management would be fine and it would allow to perform any operation from both terminal and/or Etherscan.

Copying your private key (from a single, dedicated, wallet) into a `.env` file is not a major problem if you follow some important rules such as:
- adding your key to the `.env` file when needed (and removing it as soon as you are done)
- trusting official sources only (e.g. avoid forks and always review the project code when new commits are pushed to the `main` branch)
- never commit your `.env` file (it's ignored by default if using our `.gitignore` file)
- never share your project folder with anyone (always use git repositories in order to collaborate with other team members)

Anyway, as I said in other issues: I'm gonna publish a video about how to manage your collection completely using Remix + Etherscan, while still being able to verify the contract using the CLI (without any private key, just the free API key from Etherscan).

I hope this helps, feel free reply here if you have any questions about this topic.
