### ISSUE TITLE
Modifying Contract

### ISSUE THREAD

**Issue by markjanarwin** [hashlips-lab/nft-erc721-collection#37]
What other things should I modify if I will modify the smart contract?

**Comment by liarco** [comment]
Hi @markjanarwin,
I would say there should be nothing to change in most situations, but some common cases might be the following:
1. if you change/add/remove constructor arguments to the contract, then you have to update [ContractArguments.ts](https://github.com/hashlips-lab/nft-erc721-collection/blob/main/smart-contract/config/ContractArguments.ts) accordingly
2. if you change the contract behavior you might have to update the tests accordingly, as well as the DAPP
3. if you add other contracts to your project you will have to add custom scripts in order to deploy/manage them

I can't imagine other cases at the moment, but it might depend on what you actually change.

**Comment by markjanarwin** [comment]
What if I add the ERC721A, what things should I modify?

**Comment by liarco** [comment]
I'm sorry but that's not a trivial change, I suggest you participating in the making of #29 (if you can).
