### ISSUE TITLE
Adding contract flattening feature

### ISSUE THREAD

**Issue by Jharmony** [hashlips-lab/nft-erc721-collection#38]
Great work on this project. I did notice the functionality to flatten the contract is not a feature here; could this be added?  Many thanks for considering my request.

**Comment by liarco** [comment]
Hi @Jharmony,
to be honest I don't see the code flattening as a best practice, so I would suggest avoiding it as much as possible. May I ask you to provide some information about why you would prefer to go with that option?

Thank you

**Comment by Jharmony** [comment]
> Hi @Jharmony, to be honest, I don't see the code flattening as a best practice, so I would suggest avoiding it as much as possible. May I ask you to provide some information about why you would prefer to go with that option?
> 
> Thank you

Great point; I will consider your approach as well. Thank you. I'm asking mostly because of Hashlips' YT videos, which I have faithfully followed for a couple of months now, just understood it to be best practice. I can go with either method of approaching now.

**Comment by liarco** [comment]
> Great point; I will consider your approach as well. Thank you. I'm asking mostly because of Hashlips' YT videos, which I have faithfully followed for a couple of months now, just understood it to be best practice. I can go with either method now.

Code flattening is absolutely convenient especially when dealing with Remix, because it becomes really tricky to deal with multiple files verification. By having a more structured project like this new one you can take advantage of many tools, such as the automated verification command which gives you better results with less effort.

**Just to clarify:** the code flattening works perfectly fine and I'm pretty sure people will continue to use it, but your contract on Etherscan ends up being much less readable (which is really important for users concerned about security) and it also looks less professional.

**Comment by kaanguru** [comment]
At this point Deploying contract to main ether network costs 0.158 ETH . Will **flattening smart contact** help to reduce costs?

**Comment by liarco** [comment]
Hi @kaanguru, no, it makes no difference at all. Gas cost depends on the bytecode to be deployed, but the same code produces the same bytecode even if it's flattened. Flattening simply means writing the same code into a single file instead of multiple ones, but nothing changes on the code itself.
