### ISSUE TITLE
Hello! in version 2.4.2 when I deploy DApp on Rinkeby, it says "Unsupported Network"  & hence does not let me connect to the wallet. Please answer how do I fix this?

### ISSUE THREAD

**Issue by biasaurs** [hashlips-lab/nft-erc721-collection#386]
### General information
| Description | Value |
| --- | --- |
| Project version | X.Y.Z |
| Operating system and version | ??? |
| NodeJS version | X.Y.Z |
| NPM version | X.Y.Z |
| Yarn version | X.Y.Z |
| Truffle version | X.Y.Z |

### How to Reproduce
Steps to reproduce the behavior (please provide a reproducer project for complex bugs):

**Comment by biasaurs** [comment]
Hello! in version 2.4.2 when I deploy the contract on Rinkeby, it says "Unsupported Network"  & hence does not let me connect to the wallet. Please answer how I fix this.

**Comment by biasaurs** [comment]
use version 2.4.1, it works fine

**Comment by biasaurs** [comment]
i think ver 2.4.2 was used to deploy a contract  has only minor changes, that's why it does not work on new contracts

**Comment by liarco** [comment]
Hi @biasaurs, may you please elaborate on this? Ver `2.4.2` is just a maintenance release with almost no change to the code. The "unsupported network" error depends on the collection configuration. For instance, many users have switched to Goerli instead of Rinkeby and did not update the configuration.

As far as I know the latest version is working fine if properly configured.

**Comment by jvel07** [comment]
@liarco hoping you are good! :)

I just deployed a contract on goerli using truffle, now when trying to do `yarn verify [address] --network truffle`  I get the error below. Is there something missing? (I got the etherscan's API key in the .env file).

![image](https://user-images.githubusercontent.com/10247930/191845295-454d68f0-737a-4d89-8837-a3cec1284a9e.png)

Also, I modified the `Network.ts` file to support Goerli instead of Rinkeby. Is this the correct way of changing?:
```
export const ethereumTestnet: NetworkConfigInterface = {
  chainId: 420,
  symbol: 'ETH (test)',
  blockExplorer: {
    name: 'Etherscan (Goerli)',
    generateContractUrl: (contractAddress: string) => `https://goerli.etherscan.io/address/${contractAddress}`,
    generateTransactionUrl: (transactionAddress: string) => `https://goerli.etherscan.io/tx/${transactionAddress}`,
  },
}
```
