### ISSUE TITLE
Low gas doesn't works and contract always use max gas fees

### ISSUE THREAD

**Issue by juanantonionunez** [hashlips-lab/nft-erc721-collection#40]
I was trying contract in two test projects and i've observed that gas always set in maximum fees... Maybe it's some problem with contract? See my etherscan info in one project tested with contract.

https://rinkeby.etherscan.io/address/0x7516D99bcFf74603858B2c827791400074625788

I did some tests before deploy and always set maximum gas fees.. or i'm wrong?

**Comment by liarco** [comment]
Hi @juanantonionunez,
are you concerned about the fact that most (if not all) the transactions are consuming exactly 100% of the gas set as "gas limit"?

Because if that's the case I would say [that should be absolutely fine](https://ethereum.org/en/developers/docs/gas/#what-is-gas-limit). I might be wrong but let's try to go through this together if you don't mind...

Let's consider these 3 values:
1. **gas used:** this values is the amount of GAS UNITS that have been used by the node in order to process all the operations required by the TX
2. **gas limit:** this value is expressed in GAS UNITS and it's set inside the TX in order to specify a spending limit. Let's say you accidentally run a function that enters an infinite loop, this value allows your execution to stop before burning all of your money
3. **gas fee:** this is the amount of GWEI you are gonna pay for the gas you used `(1)`. To over-simplify this, imagine to multiply your `(1)` by the current gas price in order to get `(3)` (you can find in-depth explanations about this [here](https://ethereum.org/en/developers/docs/gas/#eip-1559), as well as a cool video about `IEP1559` which defines the current gas fee system)

Now, the image you posted initially was showing `(1)` being equal to `(2)`, so basically 100% gas used... but how is `(2)` calculated? Well, to my understanding, the wallet infers that amount based on the transaction itself, so as long as your TX has predictable gas usage you will always have `(1)` = `(2)` and that's totally fine. On the other hand, if your TX is a bit less predictable, the wallet is gonna estimate the value leaving enough margin to accommodate any reasonable execution cost, so depending on the actual execution you might end up using less gas units or even running out of gas.

I hope this helps, by the way I don't have a super-strong knowledge about this specific topic, but to my experience this is how it works.

**Comment by juanantonionunez** [comment]
Thank you very much for the clarification
