### ISSUE TITLE
Network Error, Reason: could not detect network

### ISSUE THREAD

**Issue by Bickeringmonkey** [hashlips-lab/nft-erc721-collection#400]
### General information
| Description | Value |
| --- | --- |
| Project version | 2.4.2 |
| Operating system and version | MAC OS |
| NodeJS version | 16.14.0 |
| NPM version | 8.3.1 |
| Yarn version | 1.22.19 |
| Truffle version | 5.5.30 |

Good Morning,

I was wondering if anyone could help. I have been following the videos and have got to the point of opening my whitelist. When i run the command yarn whitelist-open --network truffle I get back and error code of 'Network_ERROR' and reason 'could not detect the network'.
I am on the test network Rinkeby Test Network and my config is set to:- 
testnet: Networks.ethereumTestnet,
mainnet: ethereumMainnet.

Hash lips minting-dapp server is showing me as current network: rinkeby and also displaying my correct wallet address so all seems good on that front but i have no idea why it cant seem to find the network when unpausing.

Does anyone have any ideas please as i am struggling with this one...

Many Thanks in advance.

**Comment by liarco** [comment]
Hi @Bickeringmonkey, thank you for reaching out.
This error seems to be related to Truffle. Are you sure it's correctly running on the background while you run the command? Truffle acts as a bridge between the CLI and your Metamask wallet in order to confirm any transaction, so it's impossible for the CLI to work without it.
