### ISSUE TITLE
deploy contract on rinkeby

### ISSUE THREAD

**Issue by memagroup** [hashlips-lab/nft-erc721-collection#410]
### General information
| Description | Value |
| --- | --- |
| Project version | 2.4.4 |
| Operating system and version | win10 |
| NodeJS version | 16.17.1 |
| NPM version | 8.15.0 |
| Yarn version | 1.22.19 |
| Truffle version | 5.5.31 |

### Describe the bug
when i want to deploy contract yarn deploy --network rinkeby i see the error message as below:
yarn run v1.22.19
$ hardhat run scripts/1_deploy.ts --network rinkeby
Error HH100: Network rinkeby doesn't exist

when i want run Yarn dev=server i see the error message as below :
npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating   
 ERROR  Failed to compile with 1 errors                                                       1:56:44 AM
 error  in C:\Users\90538\Desktop\123\nft-erc721-collection-2.4.4\minting-dapp\src\scripts\react\Dapp.tsx          1:56:44 AM

[tsl] ERROR in C:\Users\90538\Desktop\123\nft-erc721-collection-2.4.4\minting-dapp\src\scripts\react\Dapp.tsx(370,21)
      TS2352: Conversion of type 'Contract' to type 'nftcollection' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
  Type 'Contract' is missing the following properties from type 'nftcollection': approve, balanceOf, cost, explicitOwnershipOf, and 41 more.

Entrypoint main [big] 7.57 MiB = main.css 90.1 KiB main.js 7.48 MiB
Entrypoint _tmp_copy (127 KiB) = 3 auxiliary assets
webpack compiled with 1 error

For more info go to https://hardhat.org/HH100 or run Hardhat with --show-stack-traces
error Command failed with exit code 1.

### How to Reproduce
Steps to reproduce the behavior (please provide a reproducer project for complex bugs):

### Additional context
with above error when i connect my wallet to dapp i see the error message as below again:
Unsupported network!

**Comment by liarco** [comment]
Hi @memagroup,
the command you are using is outdated, `--network rinkeby` has been deprecated since `v2.0.0` and test networks are now simply called `testnet` in order to be able to use the same commands in any ecosystem (e.g. Ethereum, Polygon, BSC, etc.).

Also, since version `2.4.3` we moved to Goerli as the official test network because Rinkeby is gonna be deprecated soon by most of the other services out there. You can still use Rinkeby, and it's totally fine, but you have to update the collection configuration as explained in [my videos](https://github.com/hashlips-lab/nft-erc721-collection#youtube-tutorials) and use `Networks.ethereumLegacyTestnet` as explained in #404.

This should solve your issue, have a great day!

**Comment by memagroup** [comment]
thanks for your help , can you tell me on testnet as you say , how can i see my collection on opensea ? because only i can see my collection on rarible , and also how can i set royalty ? the reason i want to use lower version because the YARN DEV-SERVER command just work on version 2.1.0 , i like to use newer version but this command has a problem in last version
