### ISSUE TITLE
 It could be possible that a function was implemented to limit the maximum amount per wallet?

### ISSUE THREAD

**Issue by juanantonionunez** [hashlips-lab/nft-erc721-collection#42]
I think one of the traits that big projects have is that they usually have some kind of anti-whale mechanism to prevent the bots from lying the entire collection and leaving a lot of people without options to lie in the first few minutes. It would be wonderful if something like this were implemented. Greetings

**Comment by liarco** [comment]
Hi @juanantonionunez, I shared some thoughts about this topic in #19.

In my opinion the best "anti-whale mechanism" is building a strong community before launching the collection. Having many people genuinely interested in your tokens make any other mechanism (e.g. whitelist) work extremely well if you want to ensure the supply is spread evenly.

This is what I see most "big projects" are using successfully, but if you have any suggestions about specific features I would be happy to discuss them here.

**Comment by juanantonionunez** [comment]
I don't really agree on this point. Of course a good "anti-whale mechanism" is building a strong community before launching the collection, but in my opinion if your project is very successful and let's say your collection is going to be sold presumably in minutes you don't want someone to come along and buy 100 o 1000 at a time leaving your community (that community you have fought so hard to grow) without them having the possibility of being able to mint one of your NFTs even if they are not on the whitelist

**Comment by liarco** [comment]
I perfectly get your point, but I'm not aware of any solution that would actually work in real the real world. If a collection has such a hype that a whale could be willing to mint 100 (or even 1000) tokens in a row, then the only way to block this would be having a whitelist for the whole supply or a higher mint price (which are solutions from the community side, not in the contract code).

Any other option that I'm aware of doesn't solve the problem because anyone will always be able to create infinite wallets and mint bypassing any check if there is enough interest in doing that.

But as I said, if you have any practical example we can discuss it, I would be extremely happy to work on this.

**Comment by HaaW-NFT** [comment]
I'm having a situation where I do need to limit how many an address can mint.  I'm doing a free mint for some giveaway winners, so they'll be in a whitelist to mint for free, but each should only be able to mint 1.  Since this is free mint, not being able to restrict how many each address can mint would be devastating.  Any way of quickly adding the limit per address function into the current ERC721a contract?

**Comment by liarco** [comment]
@HaaW-NFT our whitelist already implements that behavior. What you are asking is a bit different from this topic, but our whitelist system allows only one TX per wallet address, so if you set `0` as whitelist price and `1` as `maxMintAmountPerTx` you are actually forcing max 1 token per wallet. 😉

The reason why this works with whitelists and not during public sales is because during a whitelist sale you can't create another wallet to mint again (the address must be in the whitelist), while during a public sale you can use as many addresses you want so any check is pointless.

**Comment by HaaW-NFT** [comment]
> 

Ahhh that explains a lot, thanks again :)

**Comment by juanantonionunez** [comment]
@liarco I have seen that in countless long-term projects. I could mention several that come to mind (BackLaidLlamas, Squishy, ​​Mekaverse, etc...), the reason for establishing a maximum per wallet in each phase of sale guarantees that if your project has a great roadmap and people are super interested in acquiring them because they think they will increase in value a lot or they love art because inevitably people will try to buy many at the same time and then immediately put them on the secondary market, leaving many of those who they were expectant without the opportunity to obtain them at a competitive price, this means that trust is placed in your project and that it gives it greater added value, it makes you believe in your product and that it will have so much expectation that you do not care if a single person do not go to buy more than five. And what are you telling me that they could remove one wallet and put another one in, considering that you want to sell the collection in minutes, I wouldn't even give those whales time because everything would already be sold. Do you understand the importance? Anyway, thanks again for the debate and your point of view

**Comment by liarco** [comment]
@juanantonionunez, I'm sorry... I understand what you say, but same as you think I'm wrong (and that's totally fine), I think that you are as well. I'm trying to give you some evidence of how your proposal can be cheated really easily and with a pretty low overhead, so "counting the amount of mint transactions per wallet" doesn't work.

It probably takes about 15 lines of code to:
- take ETH from a wallet
- send it to 1000 other wallets
- process 1000 mint transactions from 1000 different addresses

That may cost you around 4-7k$ to do that (with a pretty high gas price) and that's nothing if you are willing to pay for 1000 tokens from a brand new collection. Your wallet balance might get +/- 7k in a few hours without even touching your funds.

This is why I think putting my effort and wasting users gas in this feature is not worth it. I know that many collections are using these solutions as marketing claims, you can copy their code if you like that approach, but they are basically lying to the users pretending to be able to stop something that they simply can't stop. If there is enough interest in doing that, people with enough money can do it.

To wrap up: if you think those solutions can mitigate the issue, then I agree, but I also think that the trade-off is not worth it. If you think that counting the "mints per wallet" solves the issue, then we are not on the same page... it's totally fine, but you have to provide me with solid arguments for me to invest my time in this.

**Comment by HaaW-NFT** [comment]
Hey there @liarco 
Let me elaborate on my situation a bit more.  But before I do that, I should state that have no take on the subject, as I'm not very well versed in smart contrast or in coding for that matter, simply putting out an experience that just happened.

The sale was on the ETH chain, and it was a free-to-mint event so the token was listed at 0 eth, what we wanted to do was simply break the ice, as we're not a big-budget project that had the manpower or budget to build hype.  The pre-sale was for 1000 mints of our 6900 collections.   It wasn't a whitelist sale, it was a pre-sale event so all were welcome.  We had only 200 or so followers on our Twitter, and the whale dumped the token on Opeansea for 0.004 initially, and our public sale was 0.0069.

Having 500 accounts each owning 2 wouldn't be a problem, even if it's by the same person, as people on opensea tend to look at the spread of the collection.  65 owners owning 1000 NFTs usually brings up a red flag, doesn't matter what the floor is.

**Comment by HaaW-NFT** [comment]
Oh and the pre-sale lasted about 30 minutes

**Comment by liarco** [comment]
Ok @HaaW-NFT, thank you very much for the additional information. This helps a lot!

> The sale was on the ETH chain, and it was a free-to-mint event so the token was listed at 0 eth, what we wanted to do was simply break the ice, as we're not a big-budget project that had the manpower or budget to build hype.

I'm sorry to say this, but I think this was a huge mistake. Public sales can never be set at 0 price. Only a whitelist sale with 1 token per TX can be put at 0 price.
By selling your token at 0 to any possible wallet you are shooting yourself in a foot and there's nothing you can do in order to prevent that.

You shouldn't build your brand awareness through giving away stuff for free for no effort. That will never work if you want to build a strong brand/community.

**Comment by HaaW-NFT** [comment]
Aye, it's a lesson learned for us, as it's our first project in a pretty saturated niche.
