### ISSUE TITLE
What's the best way to store your NFTs/Metadata?

### ISSUE THREAD

**Issue by JohnCarp** [hashlips-lab/nft-erc721-collection#442]
First I just want to say thanks for such a great library and amazing tutorials!

My question is what's the best place to store your NFT's and metadata? Essentially I believe at some point it was Pinata but they now charge $20 a month for more then 1gb of storage. I also seen people suggest NFT.Storage which is free up to 31gb.

What do you suggest?

Thanks @liarco!

**Comment by liarco** [comment]
Hi @JohnCarp, issues should be used for bug reports only so I have to close this as "invalid".

Anyway storing assets and metadata for an NFT collection uses resources so it makes sense to pay a fee for such a service. Pinata is still the service I personally use for all of my work on IPFS (as of today). I know it's not very cheap, but it works well and I never had any issues with it. To be honest I don't trust free providers since I don't see how they can be able to continue pinning terabytes of data for free... the business model on the long run is not clear enough for me.

If you wanna know more, we often discuss alternatives and new strategies with members of the [Open Devs Crew](https://opendevs.io). 😉
