### ISSUE TITLE
Creator earnings on OpenSea - updating smart contract needed?

### ISSUE THREAD

**Issue by jvel07** [hashlips-lab/nft-erc721-collection#443]
Hi, @liarco!
As you know, from early this month OS started with the on-chain royalties enforcement feature https://support.opensea.io/hc/en-us/articles/1500009575482-How-do-creator-earnings-work-on-OpenSea-#h_01GMXN9BAZEYY02BTF3Y4TQBV3

Although it looks pretty straight forward here https://github.com/ProjectOpenSea/operator-filter-registry, just wanted to make sure how HashLips is planning to implement this since Operator Filter is intended to prevent the sale of a collection's NFTs using marketplaces that do not respect creator earnings.

This means that x2y2, blur.io, ME, and other marketplaces won't be able to show the collection after adding this filter?

**Comment by liarco** [comment]
Hi @jvel07,
we currently have no plans to add that feature to our contract (at least not any time soon and not as a default configuration), especially now that some pretty bad news came out about that solution (I discussed this with some [Open Devs Crew](https://opendevs.io) members that I helped out with the implementation).

Anyway, collections implementing that solution should still show on other marketplaces (unless they decide to skip them).

Due to lack of free time, support on public channels (like GitHub) from our team is now limited to bug/security reports only.
Discussions, news and support for general questions is reserved mainly to [ODC](https://opendevs.io) members so we can provide a better service to everyone who is supporting our work. I hope to see you there (if you wish and you can), we will provide updates about this topic as soon as we have a clear roadmap for a public release.

Thank you for your understanding.

**Comment by jvel07** [comment]
@liarco, thanks for the reply. So, in the case of not implementing this feature, it means the royalties are not going to be enforced? 
By the way, I am definitely planning to get one ODC NFT, just need a bit more eth and I will be part of the crew! :)

**Comment by jvel07** [comment]
@liarco, thanks for the reply. So, in the case of not implementing this feature, it means the royalties are not going to be enforced?
By the way, I am definitely planning to get one ODC NFT, just need a bit more eth and I will be part of the crew! :)
