### ISSUE TITLE
Minting-dapp & Smart-contract 

### ISSUE THREAD

**Issue by zueyong123** [hashlips-lab/nft-erc721-collection#46]
Hi, Liarcco, I'm currently working on the new minting dapp, which is running on VScode. Absolutely amazing really appreciate it but I ran into some problems. Recently with the contract on etherscan, when I try to mint even one NFT I get an error saying "expected to be expensive but fail, and is not recommended." I'll attach an image below not sure why this occurs. Also, I'm trying to design the minting dapp and add a background image to it. How would I go about doing so, could you recommend any languages I should learn, as well as the files I need to change to do so? Thank you so so much Liarco! Appreciate u taking the time to do so. 

![image](https://user-images.githubusercontent.com/97086494/155955168-5e3dd7c6-efac-442d-bc8d-6408de9dbe90.png)
![image](https://user-images.githubusercontent.com/97086494/155955200-d5b5cdb4-d7df-46e9-b5cd-5cad8a968de7.png)

**Comment by liarco** [comment]
Hi @zueyong123,
### Failing transaction
The failing transactions might be related to multiple issues. I see that the wallet is giving a warning about the network being busy, I would suggest trying again when the network is back to normal. You can try to run the transaction anyway and send here the Etherscan log, there you would have the exact reason why the transaction failed.

### DAPP customization
Customizing the DAPP can be very easy, all the colors can be customized quickly from the Tailwind config file:
https://github.com/hashlips-lab/nft-erc721-collection/blob/cb93309bef85043dd8dd901f122307cd4f295ab8/minting-dapp/tailwind.config.js#L10-L19

This includes the background for the token preview, while for the main BG you can put any image inside the images folder and then replace the following line:
https://github.com/hashlips-lab/nft-erc721-collection/blob/cb93309bef85043dd8dd901f122307cd4f295ab8/minting-dapp/src/styles/components/general.scss#L7

With this:
```scss
  background-image: url('../../images/background.jpg');
  @apply bg-center bg-cover bg-fixed;
```

Let me know if it works.

**Comment by zueyong123** [comment]
@liarco Thanks so much I was able to change the background for the dapp it really helped. However, I was unable to change the token preview background is there a way I could add an image for that as well? For the colours for tailwind config, only some of them worked while others I would get an error if I changed the colour. Finally is there any way I could make certain stuff on the dapp like wallet address or sale status bold & larger please? I saw ur Pause issue post I tried it and it still didn't fix it ill try to mint the NFT first and see what error I get thanks so much Liarco for ur help much love!

**Comment by liarco** [comment]
@zueyong123 colors in Tailwind have specific names, you should have autocompletion enabled in VSCode, but anyway you can find the complete list here: https://tailwindcss.com/docs/customizing-colors (you should use just the names, lowercase, no shade number... e.g. `colors.indigo`, `colors.lime`, etc.). Any attempt to use other names will result in a failing build.

In order to change the preview background you can edit the following line:
https://github.com/hashlips-lab/nft-erc721-collection/blob/cb93309bef85043dd8dd901f122307cd4f295ab8/minting-dapp/src/styles/components/minting-dapp.scss#L178

The things that you are asking me are mainly unrelated to this project. I suggest you learning `SCSS` and `Tailwind` if you want to do proper customization because I can't provide you with a full example for your specific needs, I'm sorry.

**Comment by zueyong123** [comment]
Thanks, @liarco so much really appreciate the help I'll try to learn SCSS & Tailwind again thanks for all the help I can't wait for ur new work to release really awesome keep up the great content!

**Comment by zueyong123** [comment]
> @zueyong123 colors in Tailwind have specific names, you should have autocompletion enabled in VSCode, but anyway you can find the complete list here: https://tailwindcss.com/docs/customizing-colors (you should use just the names, lowercase, no shade number... e.g. `colors.indigo`, `colors.lime`, etc.). Any attempt to use other names will result in a failing build.
> 
> In order to change the preview background you can edit the following line:
> 
> https://github.com/hashlips-lab/nft-erc721-collection/blob/cb93309bef85043dd8dd901f122307cd4f295ab8/minting-dapp/src/styles/components/minting-dapp.scss#L178
> 
> The things that you are asking me are mainly unrelated to this project. I suggest you learning `SCSS` and `Tailwind` if you want to do proper customization because I can't provide you with a full example for your specific needs, I'm sorry.

Hi, @liarco for some reason when I try to change the preview background I only have a few choices I tried using the colour names but that didn't work too this is what I got thank you.

![image](https://user-images.githubusercontent.com/97086494/156865290-47599213-2b00-4c06-bb3d-ec961962c6c4.png)

**Comment by liarco** [comment]
@zueyong123 I suggest you trying to follow my example here: https://github.com/hashlips-lab/nft-erc721-collection/issues/47#issuecomment-1055622898

There you see how to swap the `primary` color (which is `indigo` by default) with any other one from Tailwind. It also shows how to add new color names to your project. Let me know if this helps.

Also please remember that each color name contains just different shades of the same HUE, that's why you see `indigo` shades when typing `primary`.
