### ISSUE TITLE
Dapp is stuck on "Loading collection data"

### ISSUE THREAD

**Issue by HaaW-NFT** [hashlips-lab/nft-erc721-collection#48]
Hey, first I would like to say, thanks to the HashLips I'm so close to launching my own project, you guys are awesome.
I'm following along with the tutorial video and solved quite a few issues I ran into with google, but now I'm totally stuck.  I ran the "yarn dev-server", everything was running smoothly, but when I connect to my wallet from the dapp, it gets stuck at "loading collection data".  I've used Etherscan to test the contract and everything is working fine there, just can't get the dapp to initiate, please help, I'm soooo close to be able to launch the project to my followers, thanks :)
![error6](https://user-images.githubusercontent.com/100184516/155972270-5ac8140e-b59e-4509-b22d-d78467550dec.png)
![error5](https://user-images.githubusercontent.com/100184516/155972560-91f0c4dc-8635-4db6-b6b0-983d3cb8c3c9.png)
)

**Comment by HaaW-NFT** [comment]
I have set the whitelist mint price to 0, don't know if that has an effect.

**Comment by liarco** [comment]
Sorry @HaaW-NFT, I was late, but it seems like the DAPP was not able to connect to your contract, this may happen because of these reasons:
1. the contract address is not set in the configuration file https://github.com/hashlips-lab/nft-erc721-collection/blob/cb93309bef85043dd8dd901f122307cd4f295ab8/smart-contract/config/CollectionConfig.ts#L25
2. the contract address is wrong
3. you are connected to the wrong network in MetaMask

I see you closed the issue but can you tell what it was the problem so it can be useful to someone else in the future?

Thank you!

**Comment by HaaW-NFT** [comment]
> Sorry @HaaW-NFT, I was late, but it seems like the DAPP was not able to connect to your contract, this may happen because of these reasons:
> 
> 1. the contract address is not set in the configuration file https://github.com/hashlips-lab/nft-erc721-collection/blob/cb93309bef85043dd8dd901f122307cd4f295ab8/smart-contract/config/CollectionConfig.ts#L25
This was the problem, I didn't replace the null, I missed it when I was following along the video, and finally saw it when I watched it again, thanks for replying liarco :)

> 2. the contract address is wrong
> 3. you are connected to the wrong network in MetaMask
> 
> I see you closed the issue but can you tell what it was the problem so it can be useful to someone else in the future?
> 
> Thank you!
