### ISSUE TITLE
error Couldn't find the binary git

### ISSUE THREAD

**Issue by NFTSmart** [hashlips-lab/nft-erc721-collection#5]
\minting-dapp> yarn

`yarn` install v1.22.15

warning ..\..\..\..\..\package.json: No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
error Couldn't find the binary git
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command. `

**Comment by liarco** [comment]
Hi, [Git](https://en.wikipedia.org/wiki/Git) is a Version Control System that allows to track changes made to a codebase.
It's so powerful that a such tool can be used for many purposes. Here Yarn is looking for Git on your system in order to download and manage your dependencies.

Git comes pre-installed on most Linux systems, MacOS prompts you to install it the first time you try to use it, Windows needs a manual installation. By the way it's extremely simple and you can find instructions for any system here: https://git-scm.com/book/en/v2/Getting-Started-Installing-Git

**Comment by markjanarwin** [comment]
I still get this issue even though I already installed Git at https://git-scm.com/download/win

**Comment by liarco** [comment]
@markjanarwin what happens if you open the terminal on Visual Studio Code and run `git --version`?

If you get the same error, then it means that you didn't install it correctly and it might be missing in your `PATH` environment variable. In that case, this might be useful: https://stackoverflow.com/questions/26620312/git-installing-git-in-path-with-github-client-for-windows

Let me know if it works.

**Comment by markjanarwin** [comment]
this is the issue when I run git --version

https://imgur.com/HNMuUew.png

**Comment by liarco** [comment]
> this is the issue when I run git --version
> 
> https://imgur.com/HNMuUew.png

You can just drag and drop attachments here so they won't get lost in the future ;)
![HNMuUew](https://user-images.githubusercontent.com/1532277/155724877-78a63c92-1186-4a08-a274-476beb4a7242.png)

This is the same error (basically Windows cannot find the Git executable), you may try to follow the instructions from my link above, I hope it helps!

**Comment by markjanarwin** [comment]
all goods @liarco ! thank you very much it worked!
