### ISSUE TITLE
Transfer to multiple addresses in one batch

### ISSUE THREAD

**Issue by HaaW-NFT** [hashlips-lab/nft-erc721-collection#50]
Sorry for the million questions, but I just wanted to know if it's possible to transfer NFTs to multiple addresses at one transaction with the current smart contract.  I'm trying to do an airdrop to multiple accounts, and the gas fees add up.

**Comment by liarco** [comment]
Don't worry, here is a code example:
```solidity
  function mintForAddresses(uint256 _mintAmount, address[] memory _receivers) public onlyOwner {
    for (uint256 i = 0; i < _receivers.length; i++) {
      mintForAddress(_mintAmount, _receivers[i]);
    }
  }
```

Here are some gas reports for minting 10 tokens with multiple calls to `mintForAddress` vs 1 call to `mintForAddresses`... (please ignore the prices in USD since they are based on different quotations)

**Using current stable version:**
<img width="785" alt="Screen Shot 2022-03-01 at 10 55 10" src="https://user-images.githubusercontent.com/1532277/156147175-a45f546c-53c4-4824-ba22-2af28243e528.png">

**Using the upcoming version based on `ERC721A`:**
<img width="785" alt="Screen Shot 2022-03-01 at 10 52 45" src="https://user-images.githubusercontent.com/1532277/156147274-96ebf7ff-5834-4578-80b7-bbd56bf29642.png">

From what I see we might want to include this function on the contract, any feedback would be appreciated.

**Comment by HaaW-NFT** [comment]
So for that code, we can just input multiple receivers? Would be input look something like ["address1","address2","address3"]?

**Comment by liarco** [comment]
Exactly, it accepts an array of addresses.

**Comment by HaaW-NFT** [comment]
Awesome!! So input it exactly like that?  Also, I think I might have to use that on my next project because the current one is already deployed and verified, thanks for the help again liarco.

**Comment by liarco** [comment]
> Awesome!! So input it exactly like that? Also, I think I might have to use that on my next project because the current one is already deployed and verified, thanks for the help again liarco.

You should test it on the Rinkeby, using Etherscan's UI, but I think it should be fine.
