### ISSUE TITLE
Is the cost and Max mint amount for the public or for Whitelist?

### ISSUE THREAD

**Issue by BlueGreninja** [hashlips-lab/nft-erc721-collection#55]
Hi @liarco, I'm trying to deploy the smart contract ( nft-erc721-collection ) from remix on test net and I want to ask the following:
![Screenshot 2022-03-01 203344](https://user-images.githubusercontent.com/100666338/156198688-3fc8c60a-4eb9-479e-b3a9-23095b80a39b.jpg)

1) The cost that I set here will be for the Public sale or for Whitelist?

2) The Max amount per tx which is currently 2, This value will be for Whitelist or for the public?

3) The actual metadata URI ( Revealed one ), I have to provide that after the contract is deployed? or where before contract is deployed?

4) Can I verify this contract using the CLI without giving my private key in the .env file?

5) Also the Merkle tree root, how can I generate this for Whitelist if I don't deploy the contract using CLI?

**Comment by liarco** [comment]
Hi @BlueGreninja,
1. the mint price is always set to the same variable, it just gets updated through the sale steps. You should set the first price (usually whitelist)
2. same as `(1)`
3. that should be provided right before you reveal, otherwise your tokens will be exposed before you reveal. The "reveal" step requires you to run `setUriPrefix()` and `setRevealed()`
4. yes, you just need to set the same exact collection configuration and your Etherscan API key, leave the dummy data as is for the rest
5. check `/smart-contract/package.json` for all the available scripts, you have a dedicated command that generates the merkle root and prints it to the terminal

**Comment by BlueGreninja** [comment]
@liarco Collection configuration, you mean contract code? Etherscan API I get that, but I don't get the collection configuration part

**Comment by liarco** [comment]
This file contains the values used for contract deployment: https://github.com/hashlips-lab/nft-erc721-collection/blob/main/smart-contract/config/CollectionConfig.ts

Here is the reference in order to know what goes where:
https://github.com/hashlips-lab/nft-erc721-collection/blob/a43b21ee0e4e789e50315b7b584795c044460d20/smart-contract/config/ContractArguments.ts#L5-L12

This should be self-explanatory. Let me know if it's clear enough.

**Comment by liarco** [comment]
@BlueGreninja yep, that's right! 😉

**Comment by BlueGreninja** [comment]
> This file contains the values used for contract deployment: https://github.com/hashlips-lab/nft-erc721-collection/blob/main/smart-contract/config/CollectionConfig.ts
> 
> Here is the reference in order to know what goes where:
> 
> https://github.com/hashlips-lab/nft-erc721-collection/blob/a43b21ee0e4e789e50315b7b584795c044460d20/smart-contract/config/ContractArguments.ts#L5-L12
> 
> This should be self-explanatory. Let me know if it's clear enough.

Do I need to change anything here?
![image](https://user-images.githubusercontent.com/100666338/156225486-6a7df3e3-5ff3-41b9-8fd6-f779e9340900.png)

**Comment by BlueGreninja** [comment]
![image](https://user-images.githubusercontent.com/100666338/156225873-77f83e93-1f26-4e5c-b48b-7f88fe9c43b9.png)

Here is what I inputted in the remix

And this is the collectionconfig.ts file

![image](https://user-images.githubusercontent.com/100666338/156226151-8fc818c4-a6ac-4ad2-a8a7-c77d8cefb685.png)

**Comment by liarco** [comment]
@BlueGreninja, yes it looks correct!

The `ContractArguments.ts` file must remain as is, you can just use it as a reference so you know which values from the config are mandatory for validation.

**Comment by BlueGreninja** [comment]
> 

Ok now I just do yarn verify ( Contract address ) --network rinkeby

And all should be good and running right?

**Comment by liarco** [comment]
> And all should be good and running right?

Yep

**Comment by liarco** [comment]
Please ensure the following values are also the same as the ones on Remix:
https://github.com/hashlips-lab/nft-erc721-collection/blob/a43b21ee0e4e789e50315b7b584795c044460d20/smart-contract/hardhat.config.ts#L91-L99

Since you already deployed you can just change them from the code in order to test the `yarn verify` command, but for future deployments I would suggest setting Remix to the values above.

**Comment by BlueGreninja** [comment]
> Please ensure the following values are also the same as the ones on Remix:
> 
> https://github.com/hashlips-lab/nft-erc721-collection/blob/a43b21ee0e4e789e50315b7b584795c044460d20/smart-contract/hardhat.config.ts#L91-L99
> 
> Since you already deployed you can just change them from the code in order to test the `yarn verify` command, but for future deployments I would suggest setting Remix to the values above.

I deployed everything with the same values on remix, optimization with 200 runs, compiler version is 0.8.9

But still this problem is occuring

**Comment by BlueGreninja** [comment]
@liarco 
![image](https://user-images.githubusercontent.com/100666338/156229499-17a099dd-b870-4e8f-9a00-a7cbf8356294.png)
From remix


![image](https://user-images.githubusercontent.com/100666338/156229541-dedd4bd0-e308-4bb3-97b2-c0721c1fb8cb.png)

From Hardhap.config.ts file

**Comment by liarco** [comment]
@BlueGreninja something doesn't match between what you did from Remix and what is set in your project.

Common issues:
1. Constructor arguments are not marching exactly
2. Contract code is not matching exactly
3. Compiler settings are not matching exactly
4. One or more files in VSCode are not saved since last change

I can't think of anything else at the moment...

**Comment by BlueGreninja** [comment]
> @BlueGreninja something doesn't match between what you did from Remix and what is set in your project.
> 
> Common issues:
> 
> 1. Constructor arguments are not marching exactly
> 2. Contract code is not matching exactly
> 3. Compiler settings are not matching exactly
> 4. One or more files in VSCode are not saved since last change
> 
> I can't think of anything else at the moment...

@liarco What if I provide you the details of the contract, can you verify on my behalf if thats possible? its deployed on the rinkeby testnet

**Comment by BlueGreninja** [comment]
![image](https://user-images.githubusercontent.com/100666338/156231563-30b96928-7fd5-48e9-a683-e7b5e9e0de67.png)

Now I'm getting this error, cuz the cost that I set in remix was in wei

![image](https://user-images.githubusercontent.com/100666338/156231654-63a00b53-8a86-45e7-9ded-3dbd62fdb992.png)

But here I changed parseEther to formatEther cuz I saw that it was associated with the value of wei, but now I'm getting this error!

**Comment by BlueGreninja** [comment]
@liarco No I didn't, I used the wei 30000000000000000 in constructor arguments

And now I used the formatEther in contractArguments.ts file and chnaged the 0.03 ETH in CollectionConfig.ts to 30000000000000000 in wei

**Comment by BlueGreninja** [comment]
From remix
![image](https://user-images.githubusercontent.com/100666338/156233419-c49b0f8f-c3fd-47ee-901f-c1269bd931ad.png)

From VS Code CollectionConfig.ts file
![image](https://user-images.githubusercontent.com/100666338/156233487-95d49f20-83f8-4e6e-919a-97f0a554fa71.png)

From VS Code ContractArguments.ts file
![image](https://user-images.githubusercontent.com/100666338/156233554-abc08a9e-0abf-4ac4-b3fe-9e3f65cb5895.png)

**Comment by liarco** [comment]
@BlueGreninja I'm sorry but using Remix requires you to organize everything carefully and checking every single value to match exactly.
I would suggest deploying from scratch without changing the source code. My own code already converts the ETH value from the config to the proper unit.

One more thing: you are not flattening the contract, right?

**Comment by liarco** [comment]
https://github.com/hashlips-lab/nft-erc721-collection/issues/44#issuecomment-1055738285

I think this is the problem... you don't have to flatten the contract code...

**Comment by BlueGreninja** [comment]
> 

Ok I will not change any value and change back to parseEther in the ContractArguments, btw you didn't change any of this? So everything is working fine at ur end?

Also I didn't flatten the contract, just changed the contract name to Uchiha10.sol on both sides

**Comment by BlueGreninja** [comment]
Let me deploy the default file again, one more thing I am not providing the Private key on the .env file just the Etherscan API and the infura api.

**Comment by liarco** [comment]
@BlueGreninja I'm sorry but it works as intended on my side.

Also the Infura key is not needed. If you are using Remix you can skip that (but works even if you leave it there).

**Comment by BlueGreninja** [comment]
Contract address: 0x1629f300728A60bcB4805E0345B773eC57fcc705

this is my contract address which I deployed just now and still the same problem, could I dm you on discord?

**Comment by BlueGreninja** [comment]
@liarco 
![image](https://user-images.githubusercontent.com/100666338/156237202-5df3b00d-88e2-41d3-a4fc-762b9d38cb6d.png)

**Comment by BlueGreninja** [comment]
I'm getting an error after this
