### ISSUE TITLE
Whitelist Max Mint

### ISSUE THREAD

**Issue by Skellyfish** [hashlips-lab/nft-erc721-collection#6]
Hi, first thank you both so much for putting this out. I am working on deploying right now and noticed the Whitelist feature is per tx rather than per wallet. Does that mean if I set it to 5 the whitelist people can continue to purchase 5 at a time? Is there anyway to change just this whitelist function back to wallet so it prevents over minting?

Thanks!

**Comment by liarco** [comment]
Hi @Skellyfish, please take a look at this line here: https://github.com/hashlips-lab/nft-erc721-collection/blob/main/smart-contract/contracts/YourNftToken.sol#L65

Each whitelisted address will be able to make one WL transaction only.

That's why I suggest leaving the `maxMintAmountPerTx` set to `1` for the whitelist sale, here is why: imagine you set the `maxMintAmountPerTx` to `3` during the whitelist sale. People will be able to choose whether to mint 1, 2 or 3 tokens depending on how much they are willing to spend, but if they mint 1, then they will never be able to mint again at the WL price. That's because they will still be allowed to make one transaction only.

**Comment by liarco** [comment]
Please don't get me wrong: it's absolutely fine to allow minting more than 1 token during the WL sale, but be sure to explain carefully how it works to avoid misunderstanding.

**Comment by Skellyfish** [comment]
Thanks for the link! Perfect explanation. All my WL and Public mints will be the same price, so I don't need to worry about pricing. BUT to move to your point, if I did put the WL to 3 or 5, I would just need to note in my FAQ section that only 1 transaction can be made per WL address so if you want to mint the 3 or 5 you need to do it during your one transaction, correct? Then they can also mint again normally during the Public mint even if they were on the WL, or they would be removed from normal mint?

**Comment by liarco** [comment]
> so if you want to mint the 3 or 5 you need to do it during your one transaction, correct?

Yes, correct!

Limits are applied to the `whitelistMint()` function only, any public sale will be open to anyone since the `mint()` function is used instead.

**Comment by Skellyfish** [comment]
Amazing, thanks so much!

**Comment by Skellyfish** [comment]
The verification on the Rinkeby is now saying message : "Similar Match Source Code 
Note: This contract matches the deployed ByteCode of the Source Code for Contract..." then lists someones completely different address. Any idea what may be going on there? If needed, happy to email you and discuss what is needed for you to help get me through this lol.

**Comment by liarco** [comment]
> The verification on the Rinkeby is now saying message : "Similar Match Source Code Note: This contract matches the deployed ByteCode of the Source Code for Contract..." then lists someones completely different address. Any idea what may be going on there? If needed, happy to email you and discuss what is needed for you to help get me through this lol.

Hi @Skellyfish, please make proper use of GitHub issues: you should open one per topic so we will then be able to reference different issues when the same questions are asked.

Thank you for your collaboration. 😉
