### ISSUE TITLE
Which Private Key in ENV? Kindly Helpout

### ISSUE THREAD

**Issue by ArabianAce** [hashlips-lab/nft-erc721-collection#60]
Hi There, 
First of all, thanks for this Repo, I have an issue to be clarified that is under env, we need to add the private keys; are these the same private keys we export from our metamask wallets or something else? 

For using Metamask Private Keys here would not be comfortable at all as far as these are super secured using this repo.

Need a super urgent clarification.

**Comment by ArabianAce** [comment]
Also, Private keys structure shown in Hashlips video are starting from 0x..... but in my case it isn't, if it is the Metamask private key.

**Comment by liarco** [comment]
Hi @ArabianAce,
thank you for you feedback, here are some answers...

> Hi There, First of all, thanks for this Repo, I have an issue to be clarified that is under env, we need to add the private keys; are these the same private keys we export from our metamask wallets or something else?

The private key is the one provided by MetaMask. This sounds dangerous (and it is, so it must be managed in a proper way) but that's how it has been working for a long time for any project involving direct code execution. Anyway I recently [introduced a new feature](https://youtu.be/LXBFS_kXTlk) in one of my videos and this is gonna change this completely (you have to wait for our next release)

> For using Metamask Private Keys here would not be comfortable at all as far as these are super secured using this repo.

I'm not sure I understand your question, but this repo has a pretty small codebase and it's fully public, so while you always have to pay attention when running code from anyone on the internet, in this case you can read through all the code and see exactly what it does. Always do your own research and make sure you are ok with what the code does, not just with this project, any project...

> Need a super urgent clarification.

Please consider this is not a help-desk, we do our best to provide with support on stuff that is not working or by creating educational content, but you have to take your time in order to understand how stuff works and launch your project when you feel confident about your skills. You should not put yourself into a "super urgent" situation if you can't handle it.

> Also, Private keys structure shown in Hashlips video are starting from 0x..... but in my case it isn't, if it is the Metamask private key.

That's exactly the same, MetaMask returns them without the `0x` prefix which stands for "hexadecimal format", but it should work either way.

**Comment by ArabianAce** [comment]
Alright, Thanks for your Prompt response. 
Well I have a Presale on Mar 10, The reason i said "Super urgent" 

When are you releasing the next video you mentioned above? Comparing it with my Pre-sale date. Sorry for asking and thanks in advance

**Comment by liarco** [comment]
@ArabianAce the video is the one I linked above. The next release is in the making I hope to publish it before Monday, but it depends on testing results.

**Comment by ArabianAce** [comment]
Yeah, This video i have already watched. Shall wait for the next one.

Thank you for all the responses.
