### ISSUE TITLE
Predefined gas settings?

### ISSUE THREAD

**Issue by h0rizons** [hashlips-lab/nft-erc721-collection#62]
I had a txn get stuck when running `yarn presale-open --network mainnet` and was wondering if theres any way I can change the gas used when executing the script commands? I tried looking in the hardhat config file but didn't see anything.

**Comment by liarco** [comment]
Hi @h0rizons, what do you mean by "stuck"? was it set to a low gas setting so you had to wait more than expected? Is it still stuck? Dit it fail?

The CLI uses your provider (e.g. Infura) in order to estimate the gas fee, so the default values should be fine as long as you don't get stuck in the middle of a gas war for some reason.

If you really want to, you can change the settings manually following the [Hardhat documentation](https://hardhat.org/config/#json-rpc-based-networks) but **_it's not recommended_**.

Here is where you can customize those settings in your project:
https://github.com/hashlips-lab/nft-erc721-collection/blob/a43b21ee0e4e789e50315b7b584795c044460d20/smart-contract/hardhat.config.ts#L115-L129

Let me know if it helps.

**Comment by h0rizons** [comment]
When I did 'yarn presale-open' the transaction to set the cost was stuck pending for a few hours. I sent myself a 0 ETH transaction with the same nonce and got it cleared - I did push that command right as ETH was dropping and gas was shooting up, so I think that might have been the issue. 

I wanted to take a second to thank you for all your amazing work, all of the responses & time that you've put into this for the community. I really really appreciate it.

**Comment by liarco** [comment]
@h0rizons I see, unfortunately gas wars are pretty bad! 😞
Our code is not setting gas parameters, everything is handled by the provider itself which does its best in order to avoid transactions getting stuck, but it may happen. With out latest update you will be able to use Truffle Dashboard in order to run all transactions from MetaMask (and without private keys), this should make it easier to manage this kind of situations.

If you are wondering, if you already deployed your contract you should still be able to take advantage of the new version, try following these steps:
1. download the latest version
2. install all dependencies
3. run `yarn rename-contract NEW_NAME` using the same name of the contract you already deployed
4. replace the contract with the code you already deployed
5. run `yarn compile`

Then you should be able to use all the new features while still using the old Solidity code. I hope this helps.

**Comment by h0rizons** [comment]
Thank you so much! 

I also just wanted to let you know that I successfully used the ERC-721A beta build that you had posted (I think #29?) before 2.0 got pushed today. Deployed to mainnet, verified, successful pre-sale, public-sale, and reveal. 2500/3000. ![image](https://user-images.githubusercontent.com/100657102/156895310-54726669-6f39-48bf-82d9-c6e35519e792.png)

**Comment by liarco** [comment]
I'm very happy to hear that @h0rizons. I wish you the best of luck with your collection! 😃
