### ISSUE TITLE
Getting Errors installing Truffle

### ISSUE THREAD

**Issue by ArabianAce** [hashlips-lab/nft-erc721-collection#67]
Hi Liarco, 
Once again, great work in v2.0.0. I am getting this error while installing Truffle using visual studio:
![image](https://user-images.githubusercontent.com/95887192/156917544-6e5f14b0-5845-4631-98a7-b50e897d2c33.png)

I am using Apple MAcbook Pro.

**Comment by liarco** [comment]
Hi @ArabianAce, this is something that has to do with your setup and permissions. You should do a bit of research on that error because it says that you don't have permissions to install NPM modules globally.

You might solve that quickly by running as root/administrator using `sudo npm i -g truffle`.", but that should not be necessary in a properly installed environment so I suggest searching for an alternative solution on the web.

**Comment by ArabianAce** [comment]
Thanks, It did resolved the permission issue, went well until below errors appeared.

![image](https://user-images.githubusercontent.com/95887192/156918588-2e7b007d-ca1c-4492-bfbb-10d1dbb294f5.png)

I might have installed Python? But where? How? 

I am so sorry Liarco, I am not a developer, These things are hard for me to understand. The reason i opted in for a help from you.

**Comment by liarco** [comment]
I'm sorry @ArabianAce but this might be related to many things such as your OS setup, previously installed software, etc. and I never had such a problem when installing Truffle on any of my machines/servers.

You should try asking to the Truffle team on [their GitHub repo](https://github.com/trufflesuite/truffle) because maybe they already have an answer! 😉

**Comment by ArabianAce** [comment]
Thank You Liarco. I have written them
