### ISSUE TITLE
Module build failed: Module not found - nft-erc721-collection V 2.0.0

### ISSUE THREAD

**Issue by fullStackRyan** [hashlips-lab/nft-erc721-collection#69]
I have been getting this message in the minting-dapp when running `yarn dev-server`

I have checked path and it seems to be correct. Is anyone else experiencing same problems? 

Steps to reproduce: 

clone  nft-erc721-collection -v 2.0.0
run yarn in minting-dapp
run yarn dev-server in minting-dapp

` ERROR  Failed to compile with 1 errors                                                                                                                                                              12:24:34 PM

Module build failed: Module not found:
"./src/scripts/react/Dapp.tsx" contains a reference to the file "../../../../smart-contract/artifacts/contracts".
This file can not be found, please check it for typos or update it if the file got moved.

Entrypoint main [big] 7.37 MiB = main.css 56 KiB main.js 7.32 MiB
Entrypoint _tmp_copy (127 KiB) = 3 auxiliary assets
webpack compiled with 2 errors
`

**Comment by liarco** [comment]
Hi @fullStackRyan, when you interact with your contract in the `/smart-contract` folder Hardhat compiles your contract code (and typescript types). That's why you usually don't need to do that manually. But in your case it seems like you are trying to compile the DAPP before touching the smart contract so you are missing some files which are required by the DAPP.

You should run the following commands inside `/smart-contract`:
- `yarn` (install dependencies)
- `yarn compile` (compile the contract a build typings)

Then you should be able to build your DAPP. 😉

**Comment by fullStackRyan** [comment]
Ah I see. Cool Cheers. Out of interest is there going to be a on how to use V2 soon?
