### ISSUE TITLE
Rinkeby Verification Matching Another Random Deployed ByteCode

### ISSUE THREAD

**Issue by Skellyfish** [hashlips-lab/nft-erc721-collection#7]
Hi. I have successfully deployed to Rinkeby but the verification section says message : "Similar Match Source Code
Note: This contract matches the deployed ByteCode of the Source Code for Contract..." then lists someones completely different address. 

As well as when I try to run the auto verify in VS it comes back as failed because it says it is already verified. Although it is matching someone else's contract.

If needed, happy to email you and discuss what is needed for you to help get me through this.

**Comment by liarco** [comment]
Hi @Skellyfish, what you see there is completely fine. Whenever you deploy the same exact code as another contract on the blockchain then Etherscan is gonna see it and make it clear to the users by showing that message.
Imagine someone stealing the code from another project and creating a clone contract, this would prevent people from getting scammed on the Etherscan platform. (because the address alone would not be safe enough since many people wouldn't even notice the difference)

In order to avoid this for your collection, you can simply rename your contract (that's why the `yarn rename-contract NEW_NAME` command is so important and should be run as your first step when creating a new collection.

> As well as when I try to run the auto verify in VS it comes back as failed because it says it is already verified. Although it is matching someone else's contract.

That's for the same reason, when a cloned contract is found, then you won't be able to verify it.

> If needed, happy to email you and discuss what is needed for you to help get me through this.

If you ever need to get in touch with me, you can find my main contacts on my profile page: https://github.com/liarco
I'm always doing my best to reply to anyone, as long as time permits.

**Comment by Skellyfish** [comment]
Thank you! That did solve that problem! I just send you a DM on Instagram.
