### ISSUE TITLE
Opensea is not fetching the image and metadata (Hidden URI)

### ISSUE THREAD

**Issue by ArabianAce** [hashlips-lab/nft-erc721-collection#70]
Hi, Liarco,
Sorry to disturb you once again. I did all the steps according to the Daniel's video, cross-checked everything 4 times, each and everything is correct but still Opensea is not fetching the Image and Metadata from the Hiddenmetadata Uri.

<img width="771" alt="image" src="https://user-images.githubusercontent.com/95887192/156931027-3aef83a8-7d71-43fa-bcbf-3426bae9872f.png">

Thanks in Advance

**Comment by ArabianAce** [comment]
Talking about Ver. 2.0.0

**Comment by liarco** [comment]
Hi @ArabianAce, I'm sorry but you should provide further information, otherwise I won't be able to help (contract address, collection URL, etc.).

Anyway, first of all the test version of OpenSea has limited resources so sometimes it can take even hours to update with new content. You can also see the same thing in [my speedrun video](https://youtu.be/VpXJZSqLO8A?t=533): it happened to me as well and, in the end, it was OpenSea taking its time to update the data. You can also troubleshoot your metadata using this tool from OpenSea: https://docs.opensea.io/docs/4-debugging-your-metadata

I'm gonna close this since I'm pretty sure it has nothing to do with our project, but feel free to reply if you need anything else about this topic.

**Comment by ArabianAce** [comment]
Contract address: 0x37fA71b8FbD097d7f83f84541aC039E3b0B42F22 (Rinkeby Testnet)
Collection URL: https://testnets.opensea.io/collection/the-groovy-owl-society

This same issue was happening with Version 1.0 and images and metadata are still not showing (Collection URL made using Ver. 1.0  3 to 4 days ago: https://testnets.opensea.io/collection/the-groovy-owl-society-ep01) Though I am not using v1 anymore.

**Comment by liarco** [comment]
@ArabianAce please read my replies carefully because the solution to your problem is already in my message above...

I suggested using the metadata debugging tool from OpenSea, if you the instructions there you will see that OpenSea fails loading your metadata because your JSON content for the hidden metadata is invalid. You removed the credits to HashLips from your file but you left the trailing comma `,` on the line above.

**Comment by ArabianAce** [comment]
Yes. I am dumbest of the dumbs 
Now it will be a new hidden metadata after I removed the comma, i have replaced it in the smart contract, now do i need to re-deploy the contract or will it automatically take the new one? or Do i need to write it in the rinkeby etherscan for it to work? 

You are my saviour. Lots of love

**Comment by liarco** [comment]
You can simply reset the hidden metadata URI from Etherscan, then wait some time and refresh on OpenSea... it should work then.

I wish you the best of luck with you project. ;)

**Comment by ArabianAce** [comment]
All set, Thank you so so so much. 

<img width="665" alt="image" src="https://user-images.githubusercontent.com/95887192/156934001-2b8bba02-8312-4b88-82f7-634be0806335.png">

And thank you for wishing me the luck <3
