### ISSUE TITLE
DAPP Polygon - Unsupported network!

### ISSUE THREAD

**Issue by nftkk** [hashlips-lab/nft-erc721-collection#74]
Hello Guys
i have done the changes from pull requests:

addet polygon support config
makin token symbol customizabile

my smartcontract works well and is also verified.

Last step i want to test the DAPP on mumbai testnetwork. if i was on polygon the dapp days that it was an unsupported network. i did the smart contract on polygon test network.

@hashlips
maybe you can update / help to change the lines in the dapp?

i found something in the dapp.tsx

63:     const browserProvider = await detectEthereumProvider() as ExternalProvider;

i was not an professional coder :) just do it by the tutorial of haslips. thanks guys!!! 🥇

**Comment by liarco** [comment]
Hi @nftkk,
unfortunately the PR that enables support for other chains (like Polygon) is not ready for production. I can't provide you with support at the moment, but I think you are missing the configuration for the Polygon networks in your collection configuration:
https://github.com/hashlips-lab/nft-erc721-collection/blob/4727ee6f3723bfc433673c10f86ad5abe511d9f7/smart-contract/config/CollectionConfig.ts#L1-L8

There you should import the polygon networks instead of the ethereum ones (line 2) and you should use them in the config below (lines 7 and 8).

⚠️ But as I said: this feature is not ready for production. Remember that something might not work properly and we do not provide official support for unreleased features! ⚠️
