### ISSUE TITLE
Video on Netlify Monorepo deployment

### ISSUE THREAD

**Issue by fullStackRyan** [hashlips-lab/nft-erc721-collection#77]
Hi 👋 

Love the YouTube Videos! 📺 

I have a react app which displays my NFT collection. The plan is to then have the mint button link to https://mint.mywebsite.com which will then show the hashlips minting dapp. 

I'm not sure how best to deploy this. 

- should I create a folder "my folder"
- copy and paste my react app in there
- And then copy and paste the smart-contract and minting dapp in there before deploying

Thanks again for all the videos, def leaving the 5% contribution in there, you two deserve it and then some!

**Comment by liarco** [comment]
Hi @fullStackRyan,
thank you, I really appreciate your feedback.

If you are using both the contract and DAPP from this repo, then the subdomain is the way to go _(I must specify this because there are other repos from HashLips that contain older versions as a reference for the previous videos, but everyone should now use this repo)_. The DAPP is built using Webpack and it's known for using absolute URLs when referencing any resource, so you must deploy it to the root folder of your hosting service or you might end up with a blank page and a bunch of 404 errors.

> I'm not sure how best to deploy this.

Here is a quick to-do list:
1. make sure you followed all the steps required to configure and deploy your contract from the `/smart-contract` folder (remember: if you change the whitelist, then you must open the whitelist sale again and rebuild the DAPP as well)
2. build the DAPP with `yarn build` from the `/minting-dapp` folder
3. upload the content of the `/minting-dapp/public` folder to the root path of your hosting (the content should be an `index.html` file and a `build` folder)
4. enjoy, the DAPP is going to adapt to the smart contract during all the collection lifecycle! 😃

> Thanks again for all the videos, def leaving the 5% contribution in there, you two deserve it and then some!

Thank you very much, your support will help us a lot.

**Comment by fullStackRyan** [comment]
Thanks for the detailed feedback.

I have my NFT project which is a react app and it deploys automatically to Netlify when I push to main in github. 

I'm struggling on how to create a monorepo in netlify so I can have https://mywebsite.com/ and https://mint.mywebsite.com/

I then went into nft-erc721-collection project and did the build as mentioned above. I then took the public folder and when trying to paste it into my NFT project, the editor complains because I already have a public folder that belongs to my NFT project. 

Sorry I'm not doing a good job of explaining my problem. 

<img width="441" alt="Screenshot 2022-03-08 at 21 34 32" src="https://user-images.githubusercontent.com/59806496/157329026-d6823c05-041f-4090-aa9d-dfcc50558609.png">

<img width="943" alt="Screenshot 2022-03-08 at 21 28 53" src="https://user-images.githubusercontent.com/59806496/157328236-64a36262-da6c-4555-9e5a-3cd93752e06b.png">

**Comment by liarco** [comment]
@fullStackRyan unfortunately I have no experience with the Netlify service provider so I'm afraid I can't help you much, but there is one thing that I quite don't understand: maybe I'm missing something, but with the services I'm used to (e.g. DigitalOcean), I would not go for a monorepo containing both websites. I would create a really simple repo for the minting DAPP (with the built DAPP in it) and another one for the website, then I would deploy them as two distinct services.

I hope this makes sense...

**Comment by theo-raducanu** [comment]
> Thanks for the detailed feedback.
> 
> I have my NFT project which is a react app and it deploys automatically to Netlify when I push to main in github.
> 
> I'm struggling on how to create a monorepo in netlify so I can have https://mywebsite.com/ and https://mint.mywebsite.com/
> 
> I then went into nft-erc721-collection project and did the build as mentioned above. I then took the public folder and when trying to paste it into my NFT project, the editor complains because I already have a public folder that belongs to my NFT project.
> 
> Sorry I'm not doing a good job of explaining my problem.
> 
> <img alt="Screenshot 2022-03-08 at 21 34 32" width="441" src="https://user-images.githubusercontent.com/59806496/157329026-d6823c05-041f-4090-aa9d-dfcc50558609.png">
> 
> <img alt="Screenshot 2022-03-08 at 21 28 53" width="943" src="https://user-images.githubusercontent.com/59806496/157328236-64a36262-da6c-4555-9e5a-3cd93752e06b.png">

I am hosting my NFT collection website on netlify and I think that I think that I am going to add the minting dapp as a subdomain this week. Will let you know how to do it.

**Comment by fullStackRyan** [comment]
> I am hosting my NFT collection website on netlify and I think that I think that I am going to add the minting dapp as a subdomain this week. Will let you know how to do it.

Cheers, I'll keep plugging away and let you know if I have managed to do it.

**Comment by fullStackRyan** [comment]
@theo-raducanu I found this youtube video which explains how to solve my above problem: https://www.youtube.com/watch?v=7LUALv0GfYk

Hope it helps!

**Comment by liarco** [comment]
Thank you everyone for contributing. We finally have an official video about the deployment: https://youtu.be/uUrbIXUgVz4
