### ISSUE TITLE
Minting-dapp dev-server not working 

### ISSUE THREAD

**Issue by zueyong123** [hashlips-lab/nft-erc721-collection#79]
Hi @liarco, for some reason my minting dapp isn't working it all started to have problems when I tried to switch from node 16 to 14.18.2 due to hashs recommendation. After I switched it using NVM and tried this new version all problems started to occur even installing yarn in the smart-contract/dapp didn't work. However, I switched back to node v16 and it started to work again. But, when it comes to the minting-dapp I was able to install yarn but when I try to start the dev-server I get this error how do I fix this? Thanks. 

![image](https://user-images.githubusercontent.com/97086494/156962074-1e6bb9a7-d09f-43da-8c1c-03b8d954b813.png)

**Comment by liarco** [comment]
Hi @zueyong123, unfortunately you are cutting the real error above, so I need you to send a new screenshot with some additional information (please check for sensitive data, there shouldn't be any, but you never know).

For what the NodeJs version is concerned, since Node comes with NPM and Yarn along with it, I suggest sticking with the same version when both installing and using the dependencies. This should avoid incompatibility issues.
I'm currently using version `14` on my local machine, so it should work for you too, but you must do everything with that version (e.g. if you install the dependencies with one version and then you run with another you might encounter errors).

I hope this helps, let me know...

**Comment by zueyong123** [comment]
Alright, thx Liarco I was able to fix it by just restarting my PC after I changed it to node16 everything seems to be working fine.
