### ISSUE TITLE
No whitelist

### ISSUE THREAD

**Issue by thorsa12** [hashlips-lab/nft-erc721-collection#80]
Hey thanks alot! I wanna get rid of the whitelist all together. Where in the code do I have to delete things?

Regards!

**Comment by liarco** [comment]
Hi @thorsa12, I can't provide you with such an extended customization, but you can absolutely remove the code related to the whitelist sales.
There are many references to the Whitelist sale, but once you delete the functions and properties from the contract, then you should start receiving errors from the DAPP for all the places where those functions are used, so you can follow the webpack outputs and remove all the code from the DAPP too.

In my opinion, the best way would be taking time to properly inspect all the project files and remove that feature manually, but you can use my previous suggestion in order to test the system before you actually go for a complete cleanup.
