### ISSUE TITLE
Question: Regarding whitelist

### ISSUE THREAD

**Issue by mpixelz** [hashlips-lab/nft-erc721-collection#85]
Hi,
Im looking to deploy the contract on ethereum blockchain.. 
My question is.. if i want to update whitelist.json with new addresses, do i need to do anything with the contract? or just re-build the dapp and upload it? or just upload the whitelist.json file to the dapp server? 
how does that work? i mean i hope we don't have to interact with blockchain to update whitelist addresses everytime.. as then it would be better not to deploy unless whitelist shortlist is done.
I can't seem to find any answer on discord or anywhere hence asking here.
Thank you

@liarco

**Comment by liarco** [comment]
Hi @mpixelz, you should update your whitelist right before opening the whitelist sale, because you actually have to update the Merkle tree root hash on the contract and also rebuild the DAPP.

Here are the correct steps:
1. collect all the whitelist addresses
2. update the `whitelist.json` file
3. build the DAPP
4. deploy the new DAPP
5. run `yarn whitelist-open --network mainnet`

If you ever need to change something in the `whitelist.json` file after step `5`, then you will have to start again from step `2` (even if you just change one address).
