### ISSUE TITLE
Err: insufficient funds for gas

### ISSUE THREAD

**Issue by nftkk** [hashlips-lab/nft-erc721-collection#96]
Hey Guys
i did everything successfull. i just want to test if minting an nft works also. so i put an different wallet to the whitelist and try to mint. the price was 100 matic for one nft. i connect the wallet with meta mask and try to mint but get error on the dapp.

Err: insufficient funds for gas * price + value: address WALLETADRESS..................... have 95297622973218834522 want 100000000000000000000 (supplied gas 14995852)

dont give attention to the 2 minted one they are minted by the blockchain to owner.

![image](https://user-images.githubusercontent.com/101070031/157320929-da714e9c-6053-47ff-ad47-cb496086c298.png)

**Comment by liarco** [comment]
Hi @nftkk, which version are you using?

**Comment by nftkk** [comment]
i did download by the github link new yesterday. it was the 2.0.0

**Comment by liarco** [comment]
I'm sorry but Polygon is still not officially supported here, unexpected behavior can happen if you force it manually. We are working in order to include it in the next release (check #57) but it's still not ready for production, so you can test it at your own risk.

**Comment by liarco** [comment]
Sorry, just forgot to say that you can try the code from the PR mentioned above and give feedback on the PR itself so we complete the implementation thank to feedback from users like you. But I must close this because this is not actually an "issue" with any of the stable versions, we can't expect this to work properly with any possible chain at the moment. 😉
