### ISSUE TITLE
Network testnet doesn't exist

### ISSUE THREAD

**Issue by Kathywork** [hashlips-lab/nft-erc721-collection#97]
Error when deploying the contract 
I'm using testnet and rinkeby  both showing an error:
Error HH100: Network rinkeby doesn't exist
Error HH100: Network testnet doesn't exist

my npm -v 8.1.2
my node -v v16.13.2

**Comment by liarco** [comment]
Hi @Kathywork, did you fill-in all the variables in the `.env` file?

From these errors I guess you might be in one of the following 2 situations:

### Option 1
1. you want to use Truffle Dashboard instead of Infura+PrivateKeys
2. because of `1` you removed the network variables in `.env` since you don't want to use them
3. despite `2` you are still using `--network testnet` and `--network rinkeby` instead of `--network truffle` which is the one you should use in this case

### Option 2
You simply configured the `.env.example` file instead of copying it to `.env`.

But I'm using a 🔮 here so I might be wrong... 😅

**Comment by Arhamirfan** [comment]
I found a solution to this error 'Error HH100: Network rinkeby doesn't exist'..

In the smart-contract folder look for file hardhat.config.ts, in the networks their is only one truffle added.
Add the following lines as:
  networks: {
    rinkeby: {
      url: 'url here',
      accounts: ['private link here'],
      //accounts: {
          //mnemonic: MNEMONIC,
      gas: 2100000,
      gasPrice: 8000000000,
      //saveDeployments: true,
  },
    truffle: {
      url: 'http://localhost:24069/rpc',
    },
  },

But how to deploy in polygon network? Do we have to paste url of any kind?
I tried to run yarn deploy--network polygon but it is not running. How do we push this contract on polygon?

**Comment by liarco** [comment]
Sorry @Arhamirfan, but that code is totally fine and I think @Kathywork is not using Polygon.

Support for Polygon is not ready yet. You can test #57 following the instructions there, but that branch should not be used in production at the moment.

**Comment by SpiralMisT** [comment]
Hi I'm running into the same error, but I have copied over env.example to .env with infura and private keys configurations. I am not using truffle.

**Comment by liarco** [comment]
@SpiralMisT that error should appear when you specify a network that doesn't exist in your config (using the `--network`). Networks get added to the configuration if the respective env variable is set. So if you have set your env variables correctly and you are using the correct network name (`rinkeby` is called `testnet` since version `2.0.0`) then everything should work fine.

Let me know if this helps.

**Comment by SpiralMisT** [comment]
Still running into the issue using NETWORK_TESTNET_URL and NETWORK_TESTNET_PRIVATE_KEY

**Comment by liarco** [comment]
@SpiralMisT I'm unable to reproduce this error in any other way. Please, would you mind providing a reproducer project and detailed steps so we can be on the same page?

Thank you

**Comment by SpiralMisT** [comment]
I've just pulled the repo and changed the collectionconfig.ts with yarn rename-contract and changed the .env file to the endpoints/private key without changing the variable names.

**Comment by VeriumNFT** [comment]
Running the command `yarn deploy --network rinkeby` produced the HH100 error despite having a properly configured .env file with my rinkeby endpoint set for NETWORK_TESTNET_URL 

I tried running `yarn deploy -network testnet` and was able to deploy successfully. I hope this helps.

**Comment by Arhamirfan** [comment]
@liarco a huge community is using this code to deploy their collection. But I didn't understand why you not recommend to use it or to deploy their contract and minting dapp from this code.
