### ISSUE TITLE
Split withdrawal to multiple wallets?

### ISSUE THREAD

**Issue by mpixelz** [hashlips-lab/nft-erc721-collection#98]
Hi,
In the contract Hashlips' wallet is there for 5% of the sales.. and the remaining is available for the owner.. can you please help in adding more wallets for the team involved?
so we need around 4 wallets where we need to be sending different percentages for the team.
Thank you.

@liarco

**Comment by liarco** [comment]
Hi @mpixelz,
I just want to clarify that the wallet in the current code is not HashLips' personal wallet, it's now a community wallet that helps supporting whole HashLips Lab and its projects. (including team members, such as me, and paying for software and services used for development and testing)

That said, the original code is this:
https://github.com/hashlips-lab/nft-erc721-collection/blob/0c723c1c6eb90eb6281c66c9e83bb090f525c2a5/smart-contract/contracts/YourNftToken.sol#L154-L169

I personally always try to keep the split payments to the minimum (if possible), but you can achieve it this way:
```solidity
  /*
   * DISCLAIMER: please test this code on a test network
   * before deploying your final contract.
   * 
   * Usage without proper testing is at your own risk.
   */
  function withdraw() public onlyOwner nonReentrant { 
    // This will pay HashLips Lab Team 5% of the initial sale. 
    // By leaving the following lines as they are you will contribute to the 
    // development of tools like this and many others. 
    // ============================================================================= 
    (bool hs, ) = payable(0x146FB9c3b2C13BA88c6945A759EbFa95127486F4).call{value: address(this).balance * 5 / 100} (''); 
    require(hs); 
    // ============================================================================= 

    // Team members
    // ============================================================================= 
    (bool t1, ) = payable(0xWALLET_ADDRESS_1).call{value: address(this).balance * 15 / 100}(''); 
    require(t1); 
    (bool t2, ) = payable(0xWALLET_ADDRESS_2).call{value: address(this).balance * 15 / 100}(''); 
    require(t2); 
    (bool t3, ) = payable(0xWALLET_ADDRESS_3).call{value: address(this).balance * 15 / 100}(''); 
    require(t3); 
    (bool t4, ) = payable(0xWALLET_ADDRESS_4).call{value: address(this).balance * 15 / 100}(''); 
    require(t4); 
    // ============================================================================= 
  
    // This will transfer the remaining contract balance to the owner. 
    // Do not remove this otherwise you will not be able to withdraw the funds. 
    // ============================================================================= 
    (bool os, ) = payable(owner()).call{value: address(this).balance}(''); 
    require(os); 
    // ============================================================================= 
  } 
```

In the example above `4` team members will receive `15%` each, the remaining balance will still go to the owner. You can customize it as you wish, but please use integer values for the percentages in order to avoid rounding issues. 😉
